// AUTO-GENERATED from the client's file:
//   wedding_menu_recategorized_with_live_counters.xlsx  (sheet: 'Re-categorized Menu')
//
// This is the client's new, finer-grained category scheme (37 categories,
// replacing the old 9 broad ones) plus the accurate name for every one of the
// 234 dishes the client reviewed. Used by scripts/recategorizeFoods.js to
// re-point EXISTING Food documents (images/videos already uploaded) at the
// new categories and correct names, without touching imageUrl/imagePublicId.
//
// Hindi names for the 37 new categories were not supplied by the client (only
// English) -- translations below are a starting point the client can rename
// from the Admin Panel at any time; they do not affect matching logic.

export const newCategories = [
  { nameEnglish: "Aloo & Dum Specials", nameHindi: "आलू एवं दम स्पेशल", slug: "aloo-dum-specials", displayOrder: 1 },
  { nameEnglish: "Barfi", nameHindi: "बर्फी", slug: "barfi", displayOrder: 2 },
  { nameEnglish: "Chaat & Street Food", nameHindi: "चाट एवं स्ट्रीट फूड", slug: "chaat-street-food", displayOrder: 3 },
  { nameEnglish: "Cheese & Western Snacks", nameHindi: "चीज़ एवं वेस्टर्न स्नैक्स", slug: "cheese-western-snacks", displayOrder: 4 },
  { nameEnglish: "Chutney", nameHindi: "चटनी", slug: "chutney", displayOrder: 5 },
  { nameEnglish: "Cold Beverages & Juices", nameHindi: "ठंडे पेय एवं जूस", slug: "cold-beverages-juices", displayOrder: 6 },
  { nameEnglish: "Dahi Vada & Fritters", nameHindi: "दही वड़ा एवं पकौड़े", slug: "dahi-vada-fritters", displayOrder: 7 },
  { nameEnglish: "Dal", nameHindi: "दाल", slug: "dal", displayOrder: 8 },
  { nameEnglish: "Dry Sabzi", nameHindi: "सूखी सब्ज़ी", slug: "dry-sabzi", displayOrder: 9 },
  { nameEnglish: "Gujarati & Regional Snacks", nameHindi: "गुजराती एवं क्षेत्रीय नाश्ता", slug: "gujarati-regional-snacks", displayOrder: 10 },
  { nameEnglish: "Gujiya", nameHindi: "गुझिया", slug: "gujiya", displayOrder: 11 },
  { nameEnglish: "Gulab Jamun", nameHindi: "गुलाब जामुन", slug: "gulab-jamun", displayOrder: 12 },
  { nameEnglish: "Halwa", nameHindi: "हलवा", slug: "halwa", displayOrder: 13 },
  { nameEnglish: "Hot Beverages", nameHindi: "गरम पेय", slug: "hot-beverages", displayOrder: 14 },
  { nameEnglish: "Indian Snacks & Namkeen", nameHindi: "भारतीय नाश्ता एवं नमकीन", slug: "indian-snacks-namkeen", displayOrder: 15 },
  { nameEnglish: "Indo-Chinese", nameHindi: "इंडो-चाइनीज़", slug: "indo-chinese", displayOrder: 16 },
  { nameEnglish: "Jalebi, Imarti & Malpua", nameHindi: "जलेबी, इमरती एवं मालपुआ", slug: "jalebi-imarti-malpua", displayOrder: 17 },
  { nameEnglish: "Kachori & Poori Specials", nameHindi: "कचौड़ी एवं पूरी स्पेशल", slug: "kachori-poori-specials", displayOrder: 18 },
  { nameEnglish: "Kadhi", nameHindi: "कढ़ी", slug: "kadhi", displayOrder: 19 },
  { nameEnglish: "Kaju & Nut Sweets", nameHindi: "काजू एवं मेवा मिठाई", slug: "kaju-nut-sweets", displayOrder: 20 },
  { nameEnglish: "Kofta", nameHindi: "कोफ्ता", slug: "kofta", displayOrder: 21 },
  { nameEnglish: "Laddu", nameHindi: "लड्डू", slug: "laddu", displayOrder: 22 },
  { nameEnglish: "Mushroom Specials", nameHindi: "मशरूम स्पेशल", slug: "mushroom-specials", displayOrder: 23 },
  { nameEnglish: "Paneer Main Course", nameHindi: "पनीर मुख्य व्यंजन", slug: "paneer-main-course", displayOrder: 24 },
  { nameEnglish: "Papad", nameHindi: "पापड़", slug: "papad", displayOrder: 25 },
  { nameEnglish: "Pizza, Pasta & Bakery", nameHindi: "पिज़्ज़ा, पास्ता एवं बेकरी", slug: "pizza-pasta-bakery", displayOrder: 26 },
  { nameEnglish: "Poori & Chokha", nameHindi: "पूरी एवं चोखा", slug: "poori-chokha", displayOrder: 27 },
  { nameEnglish: "Raita", nameHindi: "रायता", slug: "raita", displayOrder: 28 },
  { nameEnglish: "Rasmalai & Milk Sweets", nameHindi: "रसमलाई एवं दूध की मिठाइयाँ", slug: "rasmalai-milk-sweets", displayOrder: 29 },
  { nameEnglish: "Rice & Pulao", nameHindi: "चावल एवं पुलाव", slug: "rice-pulao", displayOrder: 30 },
  { nameEnglish: "Roti & Paratha", nameHindi: "रोटी एवं पराठा", slug: "roti-paratha", displayOrder: 31 },
  { nameEnglish: "Saag", nameHindi: "साग", slug: "saag", displayOrder: 32 },
  { nameEnglish: "Salad", nameHindi: "सलाद", slug: "salad", displayOrder: 33 },
  { nameEnglish: "Soup", nameHindi: "सूप", slug: "soup", displayOrder: 34 },
  { nameEnglish: "Soya & Special Gravy Sabzi", nameHindi: "सोया एवं स्पेशल ग्रेवी सब्ज़ी", slug: "soya-special-gravy-sabzi", displayOrder: 35 },
  { nameEnglish: "Tandoori & Grilled Starters", nameHindi: "तंदूरी एवं ग्रिल्ड स्टार्टर", slug: "tandoori-grilled-starters", displayOrder: 36 },
  { nameEnglish: "Vegetable Main Course", nameHindi: "सब्ज़ी मुख्य व्यंजन", slug: "vegetable-main-course", displayOrder: 37 },
];

// Items the client flagged as uncertain/unverified spelling (see the file's
// 'Review Notes' sheet). The migration below still re-categorizes these, but
// deliberately does NOT auto-overwrite their name -- it prints them instead so
// the client can confirm the correct spelling from the Admin Panel.
export const itemsNeedingNameReview = new Set([
  "मेल दही",
  "कानी टिक्की",
  "बेस्ट पनीर",
  "मेज सोया चोखा",
  "आलू दम पटल",
  "सरन दम",
  "दही का शिकंजी",
]);

// hindiName -> { accurateEnglishName, newCategorySlug, originalCategoryLabel }
// hindiName is the join key against existing Food documents.
export const itemRecategorization = [
  { hindiName: "आलू गोभी दम", accurateEnglishName: "Aloo Gobhi Dum", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "आलू दम पटल", accurateEnglishName: "Aloo Dum (check)", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "कटहल दम", accurateEnglishName: "Kathal Dum", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "काश्मीरी दम आलू", accurateEnglishName: "Kashmiri Dum Aloo", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "बनारसी दम आलू", accurateEnglishName: "Banarasi Dum Aloo", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "बेबी कॉर्न दम", accurateEnglishName: "Baby Corn Dum", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "लौकी दम", accurateEnglishName: "Lauki Dum", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "सरन दम", accurateEnglishName: "Saran Dum (check)", newCategorySlug: "aloo-dum-specials", originalCategoryLabel: "Dum" },
  { hindiName: "कालाकंद", accurateEnglishName: "Kalakand", newCategorySlug: "barfi", originalCategoryLabel: "Mithai" },
  { hindiName: "केसर बर्फी", accurateEnglishName: "Kesar Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "गुलाबी बर्फी", accurateEnglishName: "Gulabi Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "चॉकलेट बर्फी", accurateEnglishName: "Chocolate Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "ड्राई फ्रूट बर्फी", accurateEnglishName: "Dry Fruit Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "दही बर्फी", accurateEnglishName: "Dahi Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "नारियल बर्फी", accurateEnglishName: "Nariyal Barfi (Coconut Barfi)", newCategorySlug: "barfi", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "पिस्ता बर्फी", accurateEnglishName: "Pista Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "बड़ी वाली बर्फी", accurateEnglishName: "Badi Wali Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "बर्फी", accurateEnglishName: "Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Mithai" },
  { hindiName: "बादाम बर्फी", accurateEnglishName: "Badam Barfi", newCategorySlug: "barfi", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "रवा बर्फी", accurateEnglishName: "Rava Barfi (check)", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "साधी बर्फी", accurateEnglishName: "Sadi Barfi (Plain Barfi)", newCategorySlug: "barfi", originalCategoryLabel: "Barfi" },
  { hindiName: "आलू टिक्की", accurateEnglishName: "Aloo Tikki (check)", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "गोलगप्पा", accurateEnglishName: "Golgappa", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "दही का शिकंजी", accurateEnglishName: "Dahi Ka Shikanji (check)", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "दाबेली चाट", accurateEnglishName: "Dabeli Chaat (check)", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "पाव भाजी", accurateEnglishName: "Pav Bhaji", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "फ्रूट चाट", accurateEnglishName: "Fruit Chaat (check)", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "बड़ा पाव", accurateEnglishName: "Vada Pav", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "मेल दही", accurateEnglishName: "Mel Dahi (check)", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "राज कचौरी", accurateEnglishName: "Raj Kachori", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "रैगड़ा चाट", accurateEnglishName: "Ragda Chaat (check)", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "सेव पूरी", accurateEnglishName: "Sev Puri", newCategorySlug: "chaat-street-food", originalCategoryLabel: "Fast Food" },
  { hindiName: "कॉर्न चीज़ बॉल", accurateEnglishName: "Corn Cheese Ball", newCategorySlug: "cheese-western-snacks", originalCategoryLabel: "Namkeen" },
  { hindiName: "आंवला चटनी", accurateEnglishName: "Amla Chutney", newCategorySlug: "chutney", originalCategoryLabel: "Chutney (Sweet)" },
  { hindiName: "आम चटनी", accurateEnglishName: "Aam Chutney (Mango Chutney)", newCategorySlug: "chutney", originalCategoryLabel: "Chutney (Sweet)" },
  { hindiName: "आम चटनी", accurateEnglishName: "Aam Chutney (check)", newCategorySlug: "chutney", originalCategoryLabel: "Namkeen Chaat" },
  { hindiName: "इमली चटनी", accurateEnglishName: "Imli Chutney", newCategorySlug: "chutney", originalCategoryLabel: "Chutney (Sweet)" },
  { hindiName: "खजूर इमली चटनी", accurateEnglishName: "Khajur Imli Chutney (check)", newCategorySlug: "chutney", originalCategoryLabel: "Namkeen Chaat" },
  { hindiName: "खट्टी मीठी चटनी", accurateEnglishName: "Khatti Meethi Chutney (check)", newCategorySlug: "chutney", originalCategoryLabel: "Namkeen Chaat" },
  { hindiName: "टमाटर चटनी", accurateEnglishName: "Tamatar Chutney", newCategorySlug: "chutney", originalCategoryLabel: "Chutney (Sweet)" },
  { hindiName: "पुदीना चटनी", accurateEnglishName: "Pudina Chutney", newCategorySlug: "chutney", originalCategoryLabel: "Chutney (Sweet)" },
  { hindiName: "आम पन्ना", accurateEnglishName: "Aam Panna", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "कोल्ड कॉफी", accurateEnglishName: "Cold Coffee", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "जल जीरा", accurateEnglishName: "Jal Jeera", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "पाइन एप्पल जूस", accurateEnglishName: "Pineapple Juice", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "फ्रूट जूस मिक्स", accurateEnglishName: "Fruit Juice Mix", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "बनाना जूस", accurateEnglishName: "Banana Juice", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "मैंगो जूस", accurateEnglishName: "Mango Juice", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "सिकंजी", accurateEnglishName: "Sikanji", newCategorySlug: "cold-beverages-juices", originalCategoryLabel: "Beverages" },
  { hindiName: "दही बड़ा", accurateEnglishName: "Dahi Vada", newCategorySlug: "dahi-vada-fritters", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "मूंग दही बड़ा", accurateEnglishName: "Moong Dahi Vada (check)", newCategorySlug: "dahi-vada-fritters", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "मूंग फुलौरी", accurateEnglishName: "Moong Phulori (check)", newCategorySlug: "dahi-vada-fritters", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "अरहर दाल तड़का", accurateEnglishName: "Arhar Dal Tadka", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "अरहर सादा दाल", accurateEnglishName: "Arhar Sada Dal", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "दाल तड़का", accurateEnglishName: "Dal Tadka (check)", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "दाल फ्राई", accurateEnglishName: "Dal Fry", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "दाल मखनी", accurateEnglishName: "Dal Makhani", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "मिक्स दाल", accurateEnglishName: "Mix Dal", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "मेवा दाल तड़का", accurateEnglishName: "Mewa Dal Tadka", newCategorySlug: "dal", originalCategoryLabel: "Dal" },
  { hindiName: "आलू", accurateEnglishName: "Aloo (Potato)", newCategorySlug: "dry-sabzi", originalCategoryLabel: "Dry Sabzi" },
  { hindiName: "करेला", accurateEnglishName: "Karela (Bitter Gourd)", newCategorySlug: "dry-sabzi", originalCategoryLabel: "Dry Sabzi" },
  { hindiName: "परवल", accurateEnglishName: "Parwal (Pointed Gourd)", newCategorySlug: "dry-sabzi", originalCategoryLabel: "Dry Sabzi" },
  { hindiName: "बैंगन", accurateEnglishName: "Baingan (Brinjal)", newCategorySlug: "dry-sabzi", originalCategoryLabel: "Dry Sabzi" },
  { hindiName: "भिंडी", accurateEnglishName: "Bhindi (Okra)", newCategorySlug: "dry-sabzi", originalCategoryLabel: "Dry Sabzi" },
  { hindiName: "शिमला मिर्च आलू", accurateEnglishName: "Shimla Mirch Aloo (Capsicum Potato)", newCategorySlug: "dry-sabzi", originalCategoryLabel: "Dry Sabzi" },
  { hindiName: "ढोकला", accurateEnglishName: "Dhokla", newCategorySlug: "gujarati-regional-snacks", originalCategoryLabel: "Fast Food" },
  { hindiName: "गुझिया", accurateEnglishName: "Gujiya", newCategorySlug: "gujiya", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "तिल गुड़ गुझिया", accurateEnglishName: "Til Gud Gujiya (check)", newCategorySlug: "gujiya", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "मावा गुझिया", accurateEnglishName: "Mawa Gujiya (check)", newCategorySlug: "gujiya", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "काला जामुन", accurateEnglishName: "Kala Jamun", newCategorySlug: "gulab-jamun", originalCategoryLabel: "Mithai" },
  { hindiName: "गुलाब जामुन", accurateEnglishName: "Gulab Jamun", newCategorySlug: "gulab-jamun", originalCategoryLabel: "Mithai" },
  { hindiName: "आटा हलवा", accurateEnglishName: "Atta Halwa", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "गजरेला हलवा", accurateEnglishName: "Gajrela Halwa (check)", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "गाजर हलवा", accurateEnglishName: "Gajar Halwa (Carrot Halwa)", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "बेसन हलवा", accurateEnglishName: "Besan Halwa", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "मूंग हलवा", accurateEnglishName: "Moong Halwa", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "लौकी हलवा", accurateEnglishName: "Lauki Halwa (Bottle Gourd Halwa)", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "शाही सोहन हलवा", accurateEnglishName: "Shahi Sohan Halwa", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "सिंघाड़ा हलवा", accurateEnglishName: "Singhara Halwa", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "सेव हलवा", accurateEnglishName: "Sev Halwa (check)", newCategorySlug: "halwa", originalCategoryLabel: "Halwa" },
  { hindiName: "केसर बादाम लस्सी", accurateEnglishName: "Kesar Badam Lassi", newCategorySlug: "hot-beverages", originalCategoryLabel: "Beverages" },
  { hindiName: "केसरी दूध", accurateEnglishName: "Kesari Doodh", newCategorySlug: "hot-beverages", originalCategoryLabel: "Beverages" },
  { hindiName: "कॉफी हॉट", accurateEnglishName: "Hot Coffee", newCategorySlug: "hot-beverages", originalCategoryLabel: "Beverages" },
  { hindiName: "चाय", accurateEnglishName: "Chai (Tea)", newCategorySlug: "hot-beverages", originalCategoryLabel: "Beverages" },
  { hindiName: "मसाला दूध", accurateEnglishName: "Masala Doodh (Masala Milk)", newCategorySlug: "hot-beverages", originalCategoryLabel: "Beverages" },
  { hindiName: "कानी टिक्की", accurateEnglishName: "Kaani Tikki (check)", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Namkeen" },
  { hindiName: "पनीर चिल्ला", accurateEnglishName: "Paneer Chilla", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Fast Food" },
  { hindiName: "पनीर पकोड़ा", accurateEnglishName: "Paneer Pakoda", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Namkeen" },
  { hindiName: "प्याज कचौड़ी", accurateEnglishName: "Pyaz Kachori (check)", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Namkeen" },
  { hindiName: "ब्रेड पकोड़ा", accurateEnglishName: "Bread Pakoda", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Namkeen" },
  { hindiName: "भेल कुरकुरे", accurateEnglishName: "Bhel Kurkure (check)", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Namkeen" },
  { hindiName: "मिनी वड़ा", accurateEnglishName: "Mini Vada (check)", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Namkeen" },
  { hindiName: "मूंग चिल्ला", accurateEnglishName: "Moong Chilla", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Fast Food" },
  { hindiName: "हरा भरा कबाब", accurateEnglishName: "Hara Bhara Kabab", newCategorySlug: "indian-snacks-namkeen", originalCategoryLabel: "Fast Food" },
  { hindiName: "चाउमीन", accurateEnglishName: "Chowmein", newCategorySlug: "indo-chinese", originalCategoryLabel: "Fast Food" },
  { hindiName: "नूडल्स वेज + पनीर", accurateEnglishName: "Noodles Veg + Paneer", newCategorySlug: "indo-chinese", originalCategoryLabel: "Fast Food" },
  { hindiName: "मंचूरियन", accurateEnglishName: "Manchurian", newCategorySlug: "indo-chinese", originalCategoryLabel: "Fast Food" },
  { hindiName: "मंचूरियन राइस", accurateEnglishName: "Manchurian Rice", newCategorySlug: "indo-chinese", originalCategoryLabel: "Fast Food" },
  { hindiName: "स्प्रिंग रोल", accurateEnglishName: "Spring Roll", newCategorySlug: "indo-chinese", originalCategoryLabel: "Fast Food" },
  { hindiName: "हनी चिल्ली पोटैटो", accurateEnglishName: "Honey Chilli Potato", newCategorySlug: "indo-chinese", originalCategoryLabel: "Namkeen" },
  { hindiName: "इमरती", accurateEnglishName: "Imarti", newCategorySlug: "jalebi-imarti-malpua", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "जलेबी", accurateEnglishName: "Jalebi", newCategorySlug: "jalebi-imarti-malpua", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "मालपुआ", accurateEnglishName: "Malpua (check)", newCategorySlug: "jalebi-imarti-malpua", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "कचौड़ी राजस्थानी", accurateEnglishName: "Kachori Rajasthani", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "जीरा कचौड़ी", accurateEnglishName: "Jeera Kachori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "दाल पूड़ी", accurateEnglishName: "Dal Poori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "पनीर कचौड़ी", accurateEnglishName: "Paneer Kachori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "पालक कचौड़ी", accurateEnglishName: "Palak Kachori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "बेसन पूड़ी", accurateEnglishName: "Besan Poori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "मटर कचौड़ी", accurateEnglishName: "Matar Kachori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "मूंग कचौड़ी", accurateEnglishName: "Moong Kachori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "रतन कचौड़ी", accurateEnglishName: "Ratan Kachori (check)", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "सरई पूड़ी बड़ी वाली", accurateEnglishName: "Sarai Poori (Big size)", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "हींग कचौड़ी", accurateEnglishName: "Hing Kachori", newCategorySlug: "kachori-poori-specials", originalCategoryLabel: "Kachori (Sarai Poori)" },
  { hindiName: "दही बड़ा कढ़ी", accurateEnglishName: "Dahi Vada Kadhi (check)", newCategorySlug: "kadhi", originalCategoryLabel: "Kadhi" },
  { hindiName: "पालक कढ़ी", accurateEnglishName: "Palak Kadhi", newCategorySlug: "kadhi", originalCategoryLabel: "Kadhi" },
  { hindiName: "बुढ़िया कढ़ी", accurateEnglishName: "Budhiya Kadhi (check)", newCategorySlug: "kadhi", originalCategoryLabel: "Kadhi" },
  { hindiName: "बूंदी कढ़ी", accurateEnglishName: "Boondi Kadhi", newCategorySlug: "kadhi", originalCategoryLabel: "Kadhi" },
  { hindiName: "काजू कतली", accurateEnglishName: "Kaju Katli", newCategorySlug: "kaju-nut-sweets", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "आलू कोफ्ता", accurateEnglishName: "Aloo Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "कटहल कोफ्ता", accurateEnglishName: "Kathal Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "कोफ्ता", accurateEnglishName: "Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "गोभी कोफ्ता", accurateEnglishName: "Gobhi Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "पनीर कोफ्ता", accurateEnglishName: "Paneer Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "मलाई कोफ्ता", accurateEnglishName: "Malai Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "लौकी कोफ्ता", accurateEnglishName: "Lauki Kofta", newCategorySlug: "kofta", originalCategoryLabel: "Dum" },
  { hindiName: "गुड़ लड्डू", accurateEnglishName: "Gud Laddu", newCategorySlug: "laddu", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "गोंद लड्डू", accurateEnglishName: "Gond Laddu", newCategorySlug: "laddu", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "बूंदी लड्डू", accurateEnglishName: "Boondi Laddu", newCategorySlug: "laddu", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "बेसन लड्डू", accurateEnglishName: "Besan Laddu", newCategorySlug: "laddu", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "मोतीचूर लड्डू", accurateEnglishName: "Motichoor Laddu", newCategorySlug: "laddu", originalCategoryLabel: "Barfi & Laddu" },
  { hindiName: "काजू मशरूम", accurateEnglishName: "Kaju Mushroom", newCategorySlug: "mushroom-specials", originalCategoryLabel: "Dum" },
  { hindiName: "बटर मशरूम", accurateEnglishName: "Butter Mushroom", newCategorySlug: "mushroom-specials", originalCategoryLabel: "Dum" },
  { hindiName: "मशरूम", accurateEnglishName: "Mushroom", newCategorySlug: "mushroom-specials", originalCategoryLabel: "Dum" },
  { hindiName: "मशरूम दो प्याज़ा", accurateEnglishName: "Mushroom Do Pyaza", newCategorySlug: "mushroom-specials", originalCategoryLabel: "Dum" },
  { hindiName: "कढ़ाई पनीर", accurateEnglishName: "Kadhai Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "कोरमा पनीर", accurateEnglishName: "Korma Paneer (check)", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "चिल्ली पनीर", accurateEnglishName: "Chilli Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Fast Food" },
  { hindiName: "चिल्ली पनीर", accurateEnglishName: "Chilli Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "जालफ्रेज़ी पनीर", accurateEnglishName: "Jalfrezi Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "दही पनीर", accurateEnglishName: "Dahi Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर कश्मीरी", accurateEnglishName: "Paneer Kashmiri", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर कोरमा", accurateEnglishName: "Paneer Korma", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर चोपता", accurateEnglishName: "Paneer Chopta (check)", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर टमाटर मसाला", accurateEnglishName: "Paneer Tamatar Masala", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर टिक्का मसाला", accurateEnglishName: "Paneer Tikka Masala", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर दो प्याज़ा", accurateEnglishName: "Paneer Do Pyaza", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर बटर मसाला", accurateEnglishName: "Paneer Butter Masala", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पनीर रोगन जोश", accurateEnglishName: "Paneer Rogan Josh", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "पालक पनीर", accurateEnglishName: "Palak Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "बेस्ट पनीर", accurateEnglishName: "Best Paneer (check)", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "मटर पनीर", accurateEnglishName: "Matar Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "मलाई पनीर", accurateEnglishName: "Malai Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "वेज पनीर", accurateEnglishName: "Veg Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "शाही पनीर", accurateEnglishName: "Shahi Paneer", newCategorySlug: "paneer-main-course", originalCategoryLabel: "Paneer" },
  { hindiName: "आलू पापड़", accurateEnglishName: "Aloo Papad", newCategorySlug: "papad", originalCategoryLabel: "Papad" },
  { hindiName: "उड़द दाल पापड़", accurateEnglishName: "Urad Dal Papad", newCategorySlug: "papad", originalCategoryLabel: "Papad" },
  { hindiName: "जीरा पापड़", accurateEnglishName: "Jeera Papad", newCategorySlug: "papad", originalCategoryLabel: "Papad" },
  { hindiName: "मसाला पापड़", accurateEnglishName: "Masala Papad", newCategorySlug: "papad", originalCategoryLabel: "Papad" },
  { hindiName: "मूंग दाल पापड़", accurateEnglishName: "Moong Dal Papad", newCategorySlug: "papad", originalCategoryLabel: "Papad" },
  { hindiName: "लहसुन पापड़", accurateEnglishName: "Lahsun Papad", newCategorySlug: "papad", originalCategoryLabel: "Papad" },
  { hindiName: "कॉर्न चीज़ पिज़्ज़ा", accurateEnglishName: "Corn Cheese Pizza", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Namkeen" },
  { hindiName: "गार्लिक ब्रेड", accurateEnglishName: "Garlic Bread", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Namkeen" },
  { hindiName: "पास्ता", accurateEnglishName: "Pasta", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Fast Food" },
  { hindiName: "पिज़्ज़ा", accurateEnglishName: "Pizza", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Fast Food" },
  { hindiName: "फ्रेंच फ्राई", accurateEnglishName: "French Fry", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Fast Food" },
  { hindiName: "बर्गर", accurateEnglishName: "Burger", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Fast Food" },
  { hindiName: "मैकरोनी", accurateEnglishName: "Macaroni", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Fast Food" },
  { hindiName: "सैंडविच", accurateEnglishName: "Sandwich", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Namkeen" },
  { hindiName: "हैमबर्गर", accurateEnglishName: "Hamburger", newCategorySlug: "pizza-pasta-bakery", originalCategoryLabel: "Fast Food" },
  { hindiName: "फुल पूड़ी", accurateEnglishName: "Full Poori (check)", newCategorySlug: "poori-chokha", originalCategoryLabel: "Poori" },
  { hindiName: "बैंगन भर्ता चोखा", accurateEnglishName: "Baingan Bharta Chokha", newCategorySlug: "poori-chokha", originalCategoryLabel: "Poori" },
  { hindiName: "मिक्स चोखा नाश्ता", accurateEnglishName: "Mix Chokha Nashta", newCategorySlug: "poori-chokha", originalCategoryLabel: "Poori" },
  { hindiName: "मिक्स फ्राई चोखा", accurateEnglishName: "Mix Fry Chokha", newCategorySlug: "poori-chokha", originalCategoryLabel: "Poori" },
  { hindiName: "साधी पूड़ी", accurateEnglishName: "Sadi Poori (Plain Poori)", newCategorySlug: "poori-chokha", originalCategoryLabel: "Poori" },
  { hindiName: "अनार रायता", accurateEnglishName: "Anar Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "खीरा रायता", accurateEnglishName: "Kheera Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "पाइन एप्पल रायता", accurateEnglishName: "Pineapple Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "फ्रूट रायता", accurateEnglishName: "Fruit Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "बूंदी रायता", accurateEnglishName: "Boondi Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "मिक्स वेज रायता", accurateEnglishName: "Mix Veg Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "लौकी रायता", accurateEnglishName: "Lauki Raita", newCategorySlug: "raita", originalCategoryLabel: "Dahi Vada / Raita" },
  { hindiName: "अंगूरी रसमलाई", accurateEnglishName: "Anguri Rasmalai", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "खीर कदम", accurateEnglishName: "Kheer Kadam", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "चमचम", accurateEnglishName: "Chum Chum", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "जामुन गिलौरी", accurateEnglishName: "Jamun Gilori (check)", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "रस कदम", accurateEnglishName: "Ras Kadam", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "रसगुल्ला", accurateEnglishName: "Rasgulla", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "रसमलाई", accurateEnglishName: "Rasmalai", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "राज भोग", accurateEnglishName: "Raj Bhog", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "संदेश", accurateEnglishName: "Sandesh", newCategorySlug: "rasmalai-milk-sweets", originalCategoryLabel: "Mithai" },
  { hindiName: "काश्मीरी पुलाव", accurateEnglishName: "Kashmiri Pulao", newCategorySlug: "rice-pulao", originalCategoryLabel: "Rice" },
  { hindiName: "जाफरानी पुलाव", accurateEnglishName: "Zafrani Pulao (Saffron Pulao)", newCategorySlug: "rice-pulao", originalCategoryLabel: "Rice" },
  { hindiName: "जीरा राइस", accurateEnglishName: "Jeera Rice", newCategorySlug: "rice-pulao", originalCategoryLabel: "Rice" },
  { hindiName: "पुलाव ड्राई फ्रूट", accurateEnglishName: "Pulao Dry Fruit", newCategorySlug: "rice-pulao", originalCategoryLabel: "Rice" },
  { hindiName: "प्लेन राइस", accurateEnglishName: "Plain Rice", newCategorySlug: "rice-pulao", originalCategoryLabel: "Rice" },
  { hindiName: "वेज पुलाव", accurateEnglishName: "Veg Pulao", newCategorySlug: "rice-pulao", originalCategoryLabel: "Rice" },
  { hindiName: "तन्दूर रोटी", accurateEnglishName: "Tandoor Roti", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "तवा रोटी", accurateEnglishName: "Tawa Roti (check)", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "धनिया रोटी", accurateEnglishName: "Dhania Roti", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "नान बटर रोटी", accurateEnglishName: "Naan Butter Roti", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "बाजरा रोटी", accurateEnglishName: "Bajra Roti", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "मक्का रोटी", accurateEnglishName: "Makka Roti (Corn Roti)", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "मिस्सी रोटी", accurateEnglishName: "Missi Roti", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "लच्छा पराठा", accurateEnglishName: "Laccha Paratha", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "लच्छा रोटी", accurateEnglishName: "Laccha Roti", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "श्रीमाल रोटी", accurateEnglishName: "Shrimal Roti (check)", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "सादा रोटी", accurateEnglishName: "Sada Roti (Plain Roti)", newCategorySlug: "roti-paratha", originalCategoryLabel: "Roti" },
  { hindiName: "पालक सोया साग", accurateEnglishName: "Palak Soya Saag", newCategorySlug: "saag", originalCategoryLabel: "Saag" },
  { hindiName: "मिक्स साग", accurateEnglishName: "Mix Saag", newCategorySlug: "saag", originalCategoryLabel: "Saag" },
  { hindiName: "सरसों साग", accurateEnglishName: "Sarson Saag", newCategorySlug: "saag", originalCategoryLabel: "Saag" },
  { hindiName: "गार्डन सलाद", accurateEnglishName: "Garden Salad", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "ग्रीन सलाद", accurateEnglishName: "Green Salad", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "थाई सलाद", accurateEnglishName: "Thai Salad", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "फ्रूट सलाद", accurateEnglishName: "Fruit Salad", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "मिक्स सलाद", accurateEnglishName: "Mix Salad", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "लच्छा प्याज", accurateEnglishName: "Laccha Pyaz (Onion Salad)", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "हरा सलाद", accurateEnglishName: "Hara Salad (Green Salad)", newCategorySlug: "salad", originalCategoryLabel: "Salad" },
  { hindiName: "टमाटर सूप", accurateEnglishName: "Tamatar Soup", newCategorySlug: "soup", originalCategoryLabel: "Beverages" },
  { hindiName: "कोहड़ा चना मसाला", accurateEnglishName: "Kohda Chana Masala (check)", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "पालक बैंगन आलू", accurateEnglishName: "Palak Baingan Aloo", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "मिक्स वेज फ्राई", accurateEnglishName: "Mix Veg Fry", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "मिक्स सब्जी", accurateEnglishName: "Mix Sabzi", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "मेज सोया चोखा", accurateEnglishName: "Mixed Soya Chokha (check)", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "लहसुन सब्जी", accurateEnglishName: "Lahsun Sabzi", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "सोया बड़ी मसाला", accurateEnglishName: "Soya Badi Masala (check)", newCategorySlug: "soya-special-gravy-sabzi", originalCategoryLabel: "Dum" },
  { hindiName: "तंदूरी मशरूम", accurateEnglishName: "Tandoori Mushroom", newCategorySlug: "tandoori-grilled-starters", originalCategoryLabel: "Fast Food" },
  { hindiName: "पनीर टिक्का", accurateEnglishName: "Paneer Tikka", newCategorySlug: "tandoori-grilled-starters", originalCategoryLabel: "Fast Food" },
  { hindiName: "मलाई सोया चाप", accurateEnglishName: "Malai Soya Chaap", newCategorySlug: "tandoori-grilled-starters", originalCategoryLabel: "Namkeen" },
  { hindiName: "मेयो सोया चाप", accurateEnglishName: "Mayo Soya Chaap (check)", newCategorySlug: "tandoori-grilled-starters", originalCategoryLabel: "Namkeen" },
  { hindiName: "सोयाबीन चाप", accurateEnglishName: "Soyabean Chaap", newCategorySlug: "tandoori-grilled-starters", originalCategoryLabel: "Fast Food" },
  { hindiName: "स्टफ्ड तंदूरी आलू", accurateEnglishName: "Stuffed Tandoori Aloo", newCategorySlug: "tandoori-grilled-starters", originalCategoryLabel: "Namkeen" },
  { hindiName: "भिंडी सब्जी", accurateEnglishName: "Bhindi Sabzi", newCategorySlug: "vegetable-main-course", originalCategoryLabel: "Dum" },
  { hindiName: "लौकी सब्जी", accurateEnglishName: "Lauki Sabzi", newCategorySlug: "vegetable-main-course", originalCategoryLabel: "Dum" },
];