// Sample categories and food items so the app can be demoed immediately.
// All names/descriptions can be edited from the Admin Panel afterward.

export const categories = [
  { nameHindi: "स्टार्टर", nameEnglish: "Starter", slug: "starter", displayOrder: 1 },
  { nameHindi: "मुख्य भोजन", nameEnglish: "Main Course", slug: "main-course", displayOrder: 2 },
  { nameHindi: "सब्जी", nameEnglish: "Sabji", slug: "sabji", displayOrder: 3 },
  { nameHindi: "दाल", nameEnglish: "Dal", slug: "dal", displayOrder: 4 },
  { nameHindi: "चावल", nameEnglish: "Rice", slug: "rice", displayOrder: 5 },
  { nameHindi: "रोटी/पूरी", nameEnglish: "Roti/Puri", slug: "roti-puri", displayOrder: 6 },
  { nameHindi: "मिठाई", nameEnglish: "Sweet", slug: "sweet", displayOrder: 7 },
  { nameHindi: "सलाद", nameEnglish: "Salad", slug: "salad", displayOrder: 8 },
  { nameHindi: "अन्य", nameEnglish: "Other", slug: "other", displayOrder: 9 },
];

// categorySlug is resolved to a real ObjectId by the seed script.
export const foods = [
  // ===================== DAL =====================
  { hindiName: "मेवा दाल तड़का", englishName: "Mewa Dal Tadka", description: "काजू-बादाम और मेवों से सजी घी के तड़के वाली दाल, शादी की खास दावत के लिए प्रीमियम पसंद।", categorySlug: "dal", imageQuery: "mewa dal tadka indian", isVeg: true },
  { hindiName: "अरहर दाल तड़का", englishName: "Arhar Dal Tadka", description: "अरहर दाल को जीरे और लहसुन के तड़के के साथ पकाकर बनाई गई रोज़मर्रा की पसंदीदा दाल।", categorySlug: "dal", imageQuery: "arhar dal tadka", isVeg: true },
  { hindiName: "अरहर सादा दाल", englishName: "Arhar Sada Dal", description: "बिना ज़्यादा मसालों के हल्के तड़के में पकाई गई सादी अरहर दाल, चावल के साथ बेहतरीन।", categorySlug: "dal", imageQuery: "plain arhar dal", isVeg: true },
  { hindiName: "दाल मखनी", englishName: "Dal Makhani", description: "साबुत उड़द और राजमा को मक्खन व मलाई में धीमी आंच पर पकाकर बनाई गई मशहूर पंजाबी दाल।", categorySlug: "dal", imageQuery: "dal makhani", isVeg: true },
  { hindiName: "दाल फ्राई", englishName: "Dal Fry", description: "अरहर दाल को प्याज़, टमाटर और मसालों के तड़के के साथ भूनकर तैयार की गई स्वादिष्ट दाल।", categorySlug: "dal", imageQuery: "dal fry indian", isVeg: true },
  { hindiName: "मिक्स दाल", englishName: "Mix Dal", description: "कई दालों को मिलाकर बनाई गई पौष्टिक और स्वादिष्ट दाल, देसी घी के तड़के के साथ।", categorySlug: "dal", imageQuery: "indian dal tadka", isVeg: true },
  { hindiName: "दाल तड़का", englishName: "Dal Tadka", description: "पीली मूंग-अरहर दाल पर देसी घी, जीरा और सूखी लाल मिर्च का तड़का लगाकर परोसी जाने वाली क्लासिक दाल।", categorySlug: "dal", imageQuery: "dal tadka bowl", isVeg: true },

  // ===================== ROTI / POORI (Roti, Poori, Kachori under roti-puri) =====================
  { hindiName: "मिस्सी रोटी", englishName: "Missi Roti", description: "बेसन और गेहूं के आटे को मसालों के साथ गूंथकर तवे पर सेंकी गई पौष्टिक और स्वादिष्ट रोटी।", categorySlug: "roti-puri", imageQuery: "missi roti", isVeg: true },
  { hindiName: "सादा रोटी", englishName: "Sada Roti (Plain Roti)", description: "गेहूं के आटे से बनी नरम और फूली हुई सादी रोटी, हर सब्जी और दाल के साथ परफेक्ट।", categorySlug: "roti-puri", imageQuery: "plain wheat roti", isVeg: true },
  { hindiName: "तवा रोटी", englishName: "Tawa Roti", description: "गरम तवे पर सेंकी गई मुलायम रोटी, घर जैसे स्वाद के लिए हर थाली की पहली पसंद।", categorySlug: "roti-puri", imageQuery: "tawa roti indian bread", isVeg: true },
  { hindiName: "नान बटर रोटी", englishName: "Naan Butter Roti", description: "तंदूर में सिकी नरम नान पर मक्खन की परत लगाकर परोसी जाने वाली स्वादिष्ट रोटी।", categorySlug: "roti-puri", imageQuery: "butter naan", isVeg: true },
  { hindiName: "लच्छा रोटी", englishName: "Laccha Roti", description: "परत-दर-परत तह लगाकर तवे पर सेंकी गई कुरकुरी और घी से भरपूर लच्छेदार रोटी।", categorySlug: "roti-puri", imageQuery: "laccha roti", isVeg: true },
  { hindiName: "धनिया रोटी", englishName: "Dhania Roti", description: "आटे में बारीक कटा ताज़ा धनिया मिलाकर बनाई गई खुशबूदार और स्वादिष्ट रोटी।", categorySlug: "roti-puri", imageQuery: "dhania roti coriander bread", isVeg: true },
  { hindiName: "लच्छा पराठा", englishName: "Laccha Paratha", description: "घी की कई परतों के साथ बेला और सेंका गया कुरकुरा लच्छा पराठा, हर सब्जी के साथ लाजवाब।", categorySlug: "roti-puri", imageQuery: "laccha paratha", isVeg: true },
  { hindiName: "तन्दूर रोटी", englishName: "Tandoor Roti", description: "मिट्टी के तंदूर में सिकी हुई नरम और खुशबूदार रोटी, पारंपरिक स्वाद का अनुभव।", categorySlug: "roti-puri", imageQuery: "tandoor roti", isVeg: true },
  { hindiName: "श्रीमाल रोटी", englishName: "Shrimal Roti", description: "दूध और मेवों से गूंथी गई मीठी व नरम श्रीमाल रोटी, राजस्थानी थाली की खास शान।", categorySlug: "roti-puri", imageQuery: "shrimal roti rajasthani bread", isVeg: true },
  { hindiName: "मक्का रोटी", englishName: "Makka Roti (Corn Roti)", description: "मक्के के आटे से बनी देसी घी लगी गरमागरम रोटी, सरसों के साग के साथ पारंपरिक जोड़ी।", categorySlug: "roti-puri", imageQuery: "makka roti corn bread", isVeg: true },
  { hindiName: "बाजरा रोटी", englishName: "Bajra Roti", description: "बाजरे के आटे से हाथों से बनाई गई मोटी और पौष्टिक रोटी, सर्दियों की पारंपरिक थाली का हिस्सा।", categorySlug: "roti-puri", imageQuery: "bajra roti millet bread", isVeg: true },
  { hindiName: "साधी पूड़ी", englishName: "Sadi Poori (Plain Poori)", description: "गेहूं के आटे से बेलकर गरम तेल में फुलाई गई सादी और कुरकुरी पूड़ी।", categorySlug: "roti-puri", imageQuery: "plain poori indian bread", isVeg: true },
  { hindiName: "फुल पूड़ी", englishName: "Full Poori", description: "बड़े आकार में बेली और गरम तेल में अच्छी तरह फुलाई गई पूड़ी, दावत की थाली की शान।", categorySlug: "roti-puri", imageQuery: "puffed poori", isVeg: true },
  { hindiName: "मिक्स चोखा नाश्ता", englishName: "Mix Chokha Nashta", description: "आलू, बैंगन और टमाटर को भूनकर मसालों के साथ मसल कर बनाया गया देसी मिक्स चोखा।", categorySlug: "roti-puri", imageQuery: "mix chokha bihari", isVeg: true },
  { hindiName: "मिक्स फ्राई चोखा", englishName: "Mix Fry Chokha", description: "मौसमी सब्जियों को हल्का भूनकर और मसाले मिलाकर तैयार किया गया कुरकुरा फ्राई चोखा।", categorySlug: "roti-puri", imageQuery: "mix fry chokha bihari", isVeg: true },
  { hindiName: "बैंगन भर्ता चोखा", englishName: "Baingan Bharta Chokha", description: "आग पर भूने गए बैंगन को मसल कर सरसों तेल व मसालों के साथ बनाया गया पारंपरिक चोखा।", categorySlug: "roti-puri", imageQuery: "baingan bharta chokha", isVeg: true },
  { hindiName: "सरई पूड़ी बड़ी वाली", englishName: "Sarai Poori (Big size)", description: "बड़े आकार की खस्ता कचौड़ीनुमा सरई पूड़ी, पारंपरिक बिहारी दावतों की खास डिश।", categorySlug: "roti-puri", imageQuery: "sarai poori kachori", isVeg: true },
  { hindiName: "बेसन पूड़ी", englishName: "Besan Poori", description: "बेसन और मसालों से गूंथकर तली गई खस्ता और स्वादिष्ट बेसन पूड़ी।", categorySlug: "roti-puri", imageQuery: "besan poori kachori", isVeg: true },
  { hindiName: "दाल पूड़ी", englishName: "Dal Poori", description: "उड़द दाल की पिट्ठी भरकर तली गई कुरकुरी दाल पूड़ी, नाश्ते की पारंपरिक पसंद।", categorySlug: "roti-puri", imageQuery: "dal poori kachori", isVeg: true },
  { hindiName: "पालक कचौड़ी", englishName: "Palak Kachori", description: "ताज़े पालक और मसालों की पिट्ठी भरकर तली गई हरी-भरी और खस्ता कचौड़ी।", categorySlug: "roti-puri", imageQuery: "palak kachori", isVeg: true },
  { hindiName: "जीरा कचौड़ी", englishName: "Jeera Kachori", description: "जीरे और मसालों के स्वाद से भरपूर खस्ता कचौड़ी, चाय के साथ बेहतरीन नाश्ता।", categorySlug: "roti-puri", imageQuery: "jeera kachori", isVeg: true },
  { hindiName: "हींग कचौड़ी", englishName: "Hing Kachori", description: "हींग और मसालों की खुशबूदार पिट्ठी से भरी कुरकुरी हींग कचौड़ी, पारंपरिक स्वाद की मिसाल।", categorySlug: "roti-puri", imageQuery: "hing kachori", isVeg: true },
  { hindiName: "मूंग कचौड़ी", englishName: "Moong Kachori", description: "मूंग दाल की मसालेदार पिट्ठी भरकर तली गई खस्ता और स्वादिष्ट कचौड़ी।", categorySlug: "roti-puri", imageQuery: "moong dal kachori", isVeg: true },
  { hindiName: "पनीर कचौड़ी", englishName: "Paneer Kachori", description: "मसालेदार पनीर की पिट्ठी भरकर तली गई नरम और स्वादिष्ट कचौड़ी।", categorySlug: "roti-puri", imageQuery: "paneer kachori", isVeg: true },
  { hindiName: "मटर कचौड़ी", englishName: "Matar Kachori", description: "हरे मटर को पीसकर बनाई गई मसालेदार पिट्ठी से भरी खस्ता कचौड़ी, सर्दियों की खास डिश।", categorySlug: "roti-puri", imageQuery: "matar kachori", isVeg: true },
  { hindiName: "रतन कचौड़ी", englishName: "Ratan Kachori", description: "सूखे मेवों और मसालों की खास पिट्ठी से भरी प्रीमियम रतन कचौड़ी।", categorySlug: "roti-puri", imageQuery: "ratan kachori", isVeg: true },
  { hindiName: "कचौड़ी राजस्थानी", englishName: "Kachori Rajasthani", description: "राजस्थानी अंदाज़ में तेज़ मसालों की पिट्ठी भरकर तली गई कुरकुरी कचौड़ी।", categorySlug: "roti-puri", imageQuery: "rajasthani kachori", isVeg: true },

  // ===================== RICE =====================
  { hindiName: "प्लेन राइस", englishName: "Plain Rice", description: "बासमती चावल को भाप में पकाकर तैयार किया गया सादा और खिला-खिला चावल।", categorySlug: "rice", imageQuery: "plain steamed rice", isVeg: true },
  { hindiName: "जीरा राइस", englishName: "Jeera Rice", description: "जीरे के तड़के के साथ हल्का और खुशबूदार बासमती चावल।", categorySlug: "rice", imageQuery: "jeera rice", isVeg: true },
  { hindiName: "वेज पुलाव", englishName: "Veg Pulao", description: "सुगंधित बासमती चावल में मौसमी सब्जियों और खड़े मसालों को मिलाकर पकाया गया वेज पुलाव।", categorySlug: "rice", imageQuery: "veg pulao rice", isVeg: true },
  { hindiName: "पुलाव ड्राई फ्रूट", englishName: "Pulao Dry Fruit", description: "काजू, बादाम और किशमिश से सजा हुआ खुशबूदार और शाही ड्राई फ्रूट पुलाव।", categorySlug: "rice", imageQuery: "dry fruit pulao", isVeg: true },
  { hindiName: "काश्मीरी पुलाव", englishName: "Kashmiri Pulao", description: "मेवों, फलों और केसर की खुशबू से सजा हुआ मीठा-नमकीन काश्मीरी पुलाव।", categorySlug: "rice", imageQuery: "kashmiri pulao", isVeg: true },
  { hindiName: "जाफरानी पुलाव", englishName: "Zafrani Pulao (Saffron Pulao)", description: "केसर के रंग और खुशबू से सराबोर शाही जाफरानी पुलाव, दावतों की खास शान।", categorySlug: "rice", imageQuery: "saffron pulao zafrani", isVeg: true },

  // ===================== SAAG (sabji) =====================
  { hindiName: "सरसों साग", englishName: "Sarson Saag", description: "सरसों के पत्तों को धीमी आंच पर पकाकर मक्खन के साथ परोसा गया पारंपरिक पंजाबी साग।", categorySlug: "sabji", imageQuery: "sarson saag", isVeg: true },
  { hindiName: "पालक सोया साग", englishName: "Palak Soya Saag", description: "पालक और सोया के पत्तों को मसालों के साथ पकाकर बनाया गया पौष्टिक हरा साग।", categorySlug: "sabji", imageQuery: "palak soya saag", isVeg: true },
  { hindiName: "मिक्स साग", englishName: "Mix Saag", description: "कई तरह की हरी पत्तेदार सब्जियों को मिलाकर देसी मसालों के साथ पकाया गया मिक्स साग।", categorySlug: "sabji", imageQuery: "mix saag indian", isVeg: true },

  // ===================== CHUTNEY (other) =====================
  { hindiName: "आंवला चटनी", englishName: "Amla Chutney", description: "ताज़े आंवले को मसालों के साथ पीसकर बनाई गई खट्टी-मीठी सेहतमंद चटनी।", categorySlug: "other", imageQuery: "amla chutney", isVeg: true },
  { hindiName: "आम चटनी", englishName: "Aam Chutney (Mango Chutney)", description: "कच्चे आम को गुड़ व मसालों के साथ पकाकर बनाई गई खट्टी-मीठी आम चटनी।", categorySlug: "other", imageQuery: "mango chutney", isVeg: true },
  { hindiName: "पुदीना चटनी", englishName: "Pudina Chutney", description: "ताज़े पुदीने और हरी मिर्च को पीसकर बनाई गई ठंडक भरी हरी चटनी।", categorySlug: "other", imageQuery: "mint chutney pudina", isVeg: true },
  { hindiName: "इमली चटनी", englishName: "Imli Chutney", description: "इमली और गुड़ से बनाई गई खट्टी-मीठी चटनी, हर चाट का ज़रूरी साथी।", categorySlug: "other", imageQuery: "imli tamarind chutney", isVeg: true },
  { hindiName: "टमाटर चटनी", englishName: "Tamatar Chutney", description: "पके टमाटरों को मसालों के साथ पकाकर बनाई गई खट्टी-मीठी टमाटर चटनी।", categorySlug: "other", imageQuery: "tomato chutney indian", isVeg: true },
  { hindiName: "आम चटनी", englishName: "Aam Chutney", description: "पके आम को मसालों के साथ पकाकर चाट व्यंजनों के लिए तैयार की गई मीठी आम चटनी।", categorySlug: "other", imageQuery: "aam chutney chaat", isVeg: true },
  { hindiName: "खट्टी मीठी चटनी", englishName: "Khatti Meethi Chutney", description: "इमली और गुड़ के मेल से बनी संतुलित खट्टी-मीठी चटनी, चाट व्यंजनों के लिए ज़रूरी।", categorySlug: "other", imageQuery: "khatti meethi chutney", isVeg: true },
  { hindiName: "खजूर इमली चटनी", englishName: "Khajur Imli Chutney", description: "खजूर और इमली को पकाकर बनाई गई गाढ़ी और मीठी चटनी, चाट का स्वाद बढ़ाने वाली।", categorySlug: "other", imageQuery: "khajur imli chutney dates tamarind", isVeg: true },

  // ===================== NAMKEEN CHAAT / NAMKEEN (starter) =====================
  { hindiName: "मलाई सोया चाप", englishName: "Malai Soya Chaap", description: "सोया चाप को मलाईदार मसालों में मैरिनेट कर तंदूर में भूनकर तैयार किया गया स्वादिष्ट स्टार्टर।", categorySlug: "starter", imageQuery: "malai soya chaap", isVeg: true },
  { hindiName: "मेयो सोया चाप", englishName: "Mayo Soya Chaap", description: "सोया चाप को मेयोनीज़ और मसालों के साथ मैरिनेट करके ग्रिल किया गया चटपटा स्टार्टर।", categorySlug: "starter", imageQuery: "mayo soya chaap", isVeg: true },
  { hindiName: "स्टफ्ड तंदूरी आलू", englishName: "Stuffed Tandoori Aloo", description: "पनीर व मसालों से भरे आलू को तंदूर में भूनकर बनाया गया खास स्टार्टर।", categorySlug: "starter", imageQuery: "stuffed tandoori aloo", isVeg: true },
  { hindiName: "कानी टिक्की", englishName: "Kaani Tikki", description: "आलू और मसालों से बनी कुरकुरी टिक्की, तली या शैलो फ्राई करके परोसी जाने वाली।", categorySlug: "starter", imageQuery: "aloo tikki", isVeg: true },
  { hindiName: "प्याज कचौड़ी", englishName: "Pyaz Kachori", description: "प्याज़ की मसालेदार पिट्ठी भरकर तली गई खस्ता कचौड़ी, चटपटे नाश्ते के लिए बेहतरीन।", categorySlug: "starter", imageQuery: "pyaz kachori onion kachori", isVeg: true },
  { hindiName: "मिनी वड़ा", englishName: "Mini Vada", description: "उड़द दाल के घोल से बने छोटे आकार के कुरकुरे वड़े, चटनी के साथ परोसे जाने वाले।", categorySlug: "starter", imageQuery: "mini vada indian", isVeg: true },
  { hindiName: "ब्रेड पकोड़ा", englishName: "Bread Pakoda", description: "मसालेदार आलू की स्टफिंग वाले ब्रेड को बेसन के घोल में डुबोकर तला गया कुरकुरा पकोड़ा।", categorySlug: "starter", imageQuery: "bread pakora", isVeg: true },
  { hindiName: "पनीर पकोड़ा", englishName: "Paneer Pakoda", description: "पनीर के टुकड़ों को बेसन के मसालेदार घोल में लपेटकर तला गया कुरकुरा पकोड़ा।", categorySlug: "starter", imageQuery: "paneer pakora", isVeg: true },
  { hindiName: "भेल कुरकुरे", englishName: "Bhel Kurkure", description: "मुरमुरे, सेव और चटनियों को मिलाकर बनाई गई चटपटी और कुरकुरी भेल।", categorySlug: "starter", imageQuery: "bhel puri crunchy", isVeg: true },
  { hindiName: "हनी चिल्ली पोटैटो", englishName: "Honey Chilli Potato", description: "कुरकुरे तले आलू को शहद, सोया सॉस और मिर्च के चटपटे-मीठे सॉस में टॉस किया गया स्टार्टर।", categorySlug: "starter", imageQuery: "honey chilli potato", isVeg: true },
  { hindiName: "कॉर्न चीज़ पिज़्ज़ा", englishName: "Corn Cheese Pizza", description: "स्वीट कॉर्न और पिघले चीज़ की टॉपिंग के साथ बना क्रिस्पी बेस वाला पिज़्ज़ा।", categorySlug: "starter", imageQuery: "corn cheese pizza", isVeg: true },
  { hindiName: "कॉर्न चीज़ बॉल", englishName: "Corn Cheese Ball", description: "स्वीट कॉर्न और चीज़ को गोल आकार में लपेटकर तला गया क्रिस्पी और मुलायम बॉल।", categorySlug: "starter", imageQuery: "corn cheese ball", isVeg: true },
  { hindiName: "गार्लिक ब्रेड", englishName: "Garlic Bread", description: "लहसुन और मक्खन से सजा हुआ सिका हुआ क्रिस्पी गार्लिक ब्रेड, हर उम्र की पसंद।", categorySlug: "starter", imageQuery: "garlic bread", isVeg: true },
  { hindiName: "सैंडविच", englishName: "Sandwich", description: "सब्जियों और चटनी की स्टफिंग के साथ ग्रिल किया गया हल्का और स्वादिष्ट सैंडविच।", categorySlug: "starter", imageQuery: "veg sandwich grilled", isVeg: true },

  // ===================== BEVERAGES (other) =====================
  { hindiName: "मसाला दूध", englishName: "Masala Doodh (Masala Milk)", description: "केसर, इलायची और मेवों से सजा हुआ गरम या ठंडा मसाला दूध, त्योहारों की खास पेय।", categorySlug: "other", imageQuery: "masala milk doodh", isVeg: true },
  { hindiName: "केसर बादाम लस्सी", englishName: "Kesar Badam Lassi", description: "केसर और बादाम से सजी गाढ़ी दही की मीठी और ठंडी लस्सी।", categorySlug: "other", imageQuery: "kesar badam lassi", isVeg: true },
  { hindiName: "जल जीरा", englishName: "Jal Jeera", description: "जीरा, पुदीना और काला नमक मिलाकर बनाया गया ठंडा और पाचक पेय, गर्मियों की खास पसंद।", categorySlug: "other", imageQuery: "jal jeera drink", isVeg: true },
  { hindiName: "टमाटर सूप", englishName: "Tamatar Soup", description: "पके टमाटरों को उबालकर हल्के मसालों के साथ बनाया गया गरमागरम टमाटर सूप।", categorySlug: "other", imageQuery: "tomato soup", isVeg: true },
  { hindiName: "आम पन्ना", englishName: "Aam Panna", description: "कच्चे आम को भूनकर मसालों के साथ बनाया गया खट्टा-मीठा ठंडा गर्मियों का पेय।", categorySlug: "other", imageQuery: "aam panna drink", isVeg: true },
  { hindiName: "केसरी दूध", englishName: "Kesari Doodh", description: "केसर की खुशबू और मेवों से सजा हुआ मीठा गरम दूध, खास मौकों की पारंपरिक पेय।", categorySlug: "other", imageQuery: "kesar doodh saffron milk", isVeg: true },
  { hindiName: "सिकंजी", englishName: "Sikanji", description: "नींबू, चीनी और भुने जीरे से बना ठंडा और तरोताज़ा करने वाला देसी पेय।", categorySlug: "other", imageQuery: "sikanji lemonade indian", isVeg: true },
  { hindiName: "कॉफी हॉट", englishName: "Hot Coffee", description: "दूध और कॉफी पाउडर से बनी गरमागरम फेंटी हुई कॉफी।", categorySlug: "other", imageQuery: "hot coffee cup", isVeg: true },
  { hindiName: "चाय", englishName: "Chai (Tea)", description: "अदरक और इलायची की खुशबू से भरपूर पारंपरिक भारतीय गरम चाय।", categorySlug: "other", imageQuery: "indian chai tea", isVeg: true },
  { hindiName: "कोल्ड कॉफी", englishName: "Cold Coffee", description: "दूध, कॉफी और आइसक्रीम को मिलाकर बनाई गई ठंडी और झागदार कोल्ड कॉफी।", categorySlug: "other", imageQuery: "cold coffee glass", isVeg: true },
  { hindiName: "फ्रूट जूस मिक्स", englishName: "Fruit Juice Mix", description: "मौसमी फलों को मिलाकर निकाला गया ताज़ा और पौष्टिक मिक्स फ्रूट जूस।", categorySlug: "other", imageQuery: "mixed fruit juice", isVeg: true },
  { hindiName: "मैंगो जूस", englishName: "Mango Juice", description: "पके आम से निकाला गया मीठा और गाढ़ा ताज़ा मैंगो जूस।", categorySlug: "other", imageQuery: "mango juice glass", isVeg: true },
  { hindiName: "बनाना जूस", englishName: "Banana Juice", description: "केले और दूध को मिलाकर बनाया गया गाढ़ा और पौष्टिक बनाना जूस।", categorySlug: "other", imageQuery: "banana juice shake", isVeg: true },
  { hindiName: "पाइन एप्पल जूस", englishName: "Pineapple Juice", description: "ताज़े अनानास से निकाला गया खट्टा-मीठा तरोताज़ा करने वाला जूस।", categorySlug: "other", imageQuery: "pineapple juice glass", isVeg: true },

  // ===================== FAST FOOD (starter) =====================
  { hindiName: "फ्रूट चाट", englishName: "Fruit Chaat", description: "मौसमी फलों को काटकर चाट मसाले के साथ मिलाई गई ताज़ी और सेहतमंद फ्रूट चाट।", categorySlug: "starter", imageQuery: "fruit chaat", isVeg: true },
  { hindiName: "हैमबर्गर", englishName: "Hamburger", description: "सब्जी की टिक्की, सॉस और सलाद से भरा नरम बन में परोसा जाने वाला वेज हैमबर्गर।", categorySlug: "starter", imageQuery: "veg hamburger", isVeg: true },
  { hindiName: "गोलगप्पा", englishName: "Golgappa", description: "कुरकुरी पूरियों में आलू-मसाला भरकर तीखे पानी के साथ परोसा जाने वाला लोकप्रिय स्ट्रीट स्नैक।", categorySlug: "starter", imageQuery: "golgappa panipuri", isVeg: true },
  { hindiName: "रैगड़ा चाट", englishName: "Ragda Chaat", description: "उबले सफेद मटर की मसालेदार ग्रेवी पर चटनी और सेव डालकर परोसी जाने वाली रैगड़ा चाट।", categorySlug: "starter", imageQuery: "ragda chaat", isVeg: true },
  { hindiName: "पाव भाजी", englishName: "Pav Bhaji", description: "मसालेदार मिली-जुली सब्जियों की भाजी को मक्खन लगे पाव के साथ परोसा जाने वाला मुंबई का मशहूर व्यंजन।", categorySlug: "starter", imageQuery: "pav bhaji", isVeg: true },
  { hindiName: "ढोकला", englishName: "Dhokla", description: "बेसन से भाप में बनाया गया मुलायम और स्पंजी गुजराती स्नैक, राई के तड़के के साथ।", categorySlug: "starter", imageQuery: "dhokla gujarati snack", isVeg: true },
  { hindiName: "मेल दही", englishName: "Mel Dahi", description: "दही के साथ मसाले और चटनी मिलाकर बनाया गया ठंडा और चटपटा दही-आधारित स्नैक।", categorySlug: "starter", imageQuery: "dahi chaat", isVeg: true },
  { hindiName: "सेव पूरी", englishName: "Sev Puri", description: "छोटी कुरकुरी पूरियों पर आलू, चटनी और सेव सजाकर बनाई गई चटपटी सेव पूरी।", categorySlug: "starter", imageQuery: "sev puri chaat", isVeg: true },
  { hindiName: "राज कचौरी", englishName: "Raj Kachori", description: "बड़ी कुरकुरी कचौरी में दही, चटनी और स्प्राउट्स भरकर परोसी जाने वाली राजस्थानी खास चाट।", categorySlug: "starter", imageQuery: "raj kachori", isVeg: true },
  { hindiName: "चाउमीन", englishName: "Chowmein", description: "सब्जियों के साथ सॉस में भूनकर बनाई गई इंडो-चाइनीज़ स्टाइल चटपटी चाउमीन।", categorySlug: "starter", imageQuery: "veg chowmein noodles", isVeg: true },
  { hindiName: "नूडल्स वेज + पनीर", englishName: "Noodles Veg + Paneer", description: "सब्जियों और पनीर के टुकड़ों के साथ भूनकर बनाए गए चटपटे नूडल्स।", categorySlug: "starter", imageQuery: "veg paneer noodles", isVeg: true },
  { hindiName: "फ्रेंच फ्राई", englishName: "French Fry", description: "आलू की पतली कतरनों को कुरकुरा होने तक तलकर नमक व मसाले के साथ परोसा गया स्नैक।", categorySlug: "starter", imageQuery: "french fries", isVeg: true },
  { hindiName: "पिज़्ज़ा", englishName: "Pizza", description: "क्रिस्पी बेस पर चीज़ और मिली-जुली सब्जियों की टॉपिंग के साथ बेक किया गया पिज़्ज़ा।", categorySlug: "starter", imageQuery: "veg pizza", isVeg: true },
  { hindiName: "बर्गर", englishName: "Burger", description: "मसालेदार आलू की पैटी, सलाद और सॉस से भरा नरम बन में परोसा जाने वाला बर्गर।", categorySlug: "starter", imageQuery: "veg burger", isVeg: true },
  { hindiName: "स्प्रिंग रोल", englishName: "Spring Roll", description: "बारीक कटी सब्जियों को पतली परत में लपेटकर कुरकुरा तला गया स्प्रिंग रोल।", categorySlug: "starter", imageQuery: "veg spring roll", isVeg: true },
  { hindiName: "पास्ता", englishName: "Pasta", description: "सफेद या लाल सॉस में सब्जियों के साथ पकाया गया चीज़ी और स्वादिष्ट पास्ता।", categorySlug: "starter", imageQuery: "veg pasta", isVeg: true },
  { hindiName: "मैकरोनी", englishName: "Macaroni", description: "मसालेदार चीज़ी सॉस में सब्जियों के साथ पकाई गई मैकरोनी पास्ता।", categorySlug: "starter", imageQuery: "macaroni pasta", isVeg: true },
  { hindiName: "मंचूरियन", englishName: "Manchurian", description: "सब्जियों के गोले तलकर तीखी-चटपटी सॉस में डुबोकर बनाया गया इंडो-चाइनीज़ मंचूरियन।", categorySlug: "starter", imageQuery: "veg manchurian", isVeg: true },
  { hindiName: "मंचूरियन राइस", englishName: "Manchurian Rice", description: "तले हुए राइस के साथ परोसा गया चटपटा वेज मंचूरियन कॉम्बो।", categorySlug: "starter", imageQuery: "manchurian rice combo", isVeg: true },
  { hindiName: "चिल्ली पनीर", englishName: "Chilli Paneer", description: "तले हुए पनीर के टुकड़ों को शिमला मिर्च और तीखी सॉस के साथ भूनकर बनाया गया चटपटा व्यंजन।", categorySlug: "starter", imageQuery: "chilli paneer", isVeg: true },
  { hindiName: "पनीर टिक्का", englishName: "Paneer Tikka", description: "तंदूर में भुना हुआ मसालेदार पनीर, स्टार्टर के लिए एक बेहतरीन विकल्प।", categorySlug: "starter", imageQuery: "paneer tikka starter", isVeg: true },
  { hindiName: "पनीर चिल्ला", englishName: "Paneer Chilla", description: "बेसन के घोल में मसाले और पनीर मिलाकर तवे पर सेंका गया पौष्टिक चिल्ला।", categorySlug: "starter", imageQuery: "paneer chilla besan", isVeg: true },
  { hindiName: "मूंग चिल्ला", englishName: "Moong Chilla", description: "भीगी मूंग दाल को पीसकर मसालों के साथ तवे पर सेंका गया हल्का और सेहतमंद चिल्ला।", categorySlug: "starter", imageQuery: "moong dal chilla", isVeg: true },
  { hindiName: "तंदूरी मशरूम", englishName: "Tandoori Mushroom", description: "मसालेदार दही में मैरिनेट कर तंदूर में भुने गए मशरूम, धुएँदार स्वाद वाला स्टार्टर।", categorySlug: "starter", imageQuery: "tandoori mushroom", isVeg: true },
  { hindiName: "बड़ा पाव", englishName: "Vada Pav", description: "मसालेदार आलू वड़े को पाव के बीच चटनी के साथ भरकर परोसा गया मुंबई का मशहूर स्नैक।", categorySlug: "starter", imageQuery: "vada pav", isVeg: true },
  { hindiName: "दाबेली चाट", englishName: "Dabeli Chaat", description: "मसालेदार आलू की स्टफिंग को पाव में भरकर सेव व चटनी के साथ परोसी गई कच्छी दाबेली।", categorySlug: "starter", imageQuery: "dabeli chaat", isVeg: true },
  { hindiName: "आलू टिक्की", englishName: "Aloo Tikki", description: "उबले आलू और मसालों से बनी सुनहरी कुरकुरी टिक्की, चटनी के साथ परोसी जाने वाली।", categorySlug: "starter", imageQuery: "aloo tikki chaat", isVeg: true },
  { hindiName: "हरा भरा कबाब", englishName: "Hara Bhara Kabab", description: "पालक, मटर और आलू को मिलाकर बनाया गया हरा-भरा और सेहतमंद तला हुआ कबाब।", categorySlug: "starter", imageQuery: "hara bhara kabab", isVeg: true },
  { hindiName: "दही का शिकंजी", englishName: "Dahi Ka Shikanji", description: "दही और मसालों को मथकर बनाया गया ठंडा, गाढ़ा और तरोताज़ा करने वाला पेय।", categorySlug: "starter", imageQuery: "dahi shikanji drink", isVeg: true },
  { hindiName: "सोयाबीन चाप", englishName: "Soyabean Chaap", description: "सोया चाप को मसालों में मैरिनेट कर तंदूर में भूनकर बनाया गया स्वादिष्ट स्टार्टर।", categorySlug: "starter", imageQuery: "soya chaap tandoori", isVeg: true },

  // ===================== PANEER (main-course) =====================
  { hindiName: "पनीर बटर मसाला", englishName: "Paneer Butter Masala", description: "मलाईदार टमाटर-मक्खन की ग्रेवी में पनीर के टुकड़े पकाकर बनाई गई सबसे लोकप्रिय पनीर डिश।", categorySlug: "main-course", imageQuery: "paneer butter masala", isVeg: true },
  { hindiName: "शाही पनीर", englishName: "Shahi Paneer", description: "मेवों और मलाई से बनी शाही ग्रेवी में पनीर पकाकर तैयार किया गया प्रीमियम व्यंजन।", categorySlug: "main-course", imageQuery: "shahi paneer curry", isVeg: true },
  { hindiName: "पालक पनीर", englishName: "Palak Paneer", description: "ताज़े पालक की प्यूरी में पनीर के टुकड़े पकाकर बनाया गया पौष्टिक और स्वादिष्ट व्यंजन।", categorySlug: "main-course", imageQuery: "palak paneer curry", isVeg: true },
  { hindiName: "पनीर दो प्याज़ा", englishName: "Paneer Do Pyaza", description: "प्याज़ के बड़े टुकड़ों के साथ मसालेदार ग्रेवी में पकाया गया पनीर दो प्याज़ा।", categorySlug: "main-course", imageQuery: "paneer do pyaza", isVeg: true },
  { hindiName: "बेस्ट पनीर", englishName: "Best Paneer", description: "देसी मसालों की खास ग्रेवी में पकाया गया शेफ का स्पेशल पनीर व्यंजन।", categorySlug: "main-course", imageQuery: "special paneer curry", isVeg: true },
  { hindiName: "कढ़ाई पनीर", englishName: "Kadhai Paneer", description: "शिमला मिर्च और कढ़ाई मसाले के साथ भूनकर बनाया गया चटपटा पनीर व्यंजन।", categorySlug: "main-course", imageQuery: "kadhai paneer", isVeg: true },
  { hindiName: "मटर पनीर", englishName: "Matar Paneer", description: "हरे मटर और पनीर को टमाटर की ग्रेवी में पकाकर बनाया गया घरेलू स्वाद वाला व्यंजन।", categorySlug: "main-course", imageQuery: "matar paneer curry", isVeg: true },
  { hindiName: "जालफ्रेज़ी पनीर", englishName: "Jalfrezi Paneer", description: "रंग-बिरंगी शिमला मिर्च और सब्जियों के साथ भूनकर बनाया गया पनीर जालफ्रेज़ी।", categorySlug: "main-course", imageQuery: "paneer jalfrezi", isVeg: true },
  { hindiName: "मलाई पनीर", englishName: "Malai Paneer", description: "मलाई और काजू की मुलायम ग्रेवी में पनीर पकाकर बनाया गया हल्के मसाले वाला व्यंजन।", categorySlug: "main-course", imageQuery: "malai paneer curry", isVeg: true },
  { hindiName: "कोरमा पनीर", englishName: "Korma Paneer", description: "दही, मेवों और खड़े मसालों की सुगंधित ग्रेवी में पकाया गया पनीर कोरमा।", categorySlug: "main-course", imageQuery: "paneer korma", isVeg: true },
  { hindiName: "वेज पनीर", englishName: "Veg Paneer", description: "मिली-जुली सब्जियों के साथ पनीर को मसालेदार ग्रेवी में पकाकर बनाया गया व्यंजन।", categorySlug: "main-course", imageQuery: "veg paneer curry", isVeg: true },
  { hindiName: "पनीर रोगन जोश", englishName: "Paneer Rogan Josh", description: "कश्मीरी मसालों की गहरी लाल ग्रेवी में पनीर पकाकर बनाया गया खास व्यंजन।", categorySlug: "main-course", imageQuery: "paneer rogan josh", isVeg: true },
  { hindiName: "पनीर चोपता", englishName: "Paneer Chopta", description: "पहाड़ी अंदाज़ के मसालों के साथ पकाया गया पनीर का खास व्यंजन।", categorySlug: "main-course", imageQuery: "paneer curry pahadi", isVeg: true },
  { hindiName: "चिल्ली पनीर", englishName: "Chilli Paneer", description: "तीखी सॉस और शिमला मिर्च के साथ ग्रेवी में पकाया गया चिल्ली पनीर।", categorySlug: "main-course", imageQuery: "chilli paneer gravy", isVeg: true },
  { hindiName: "पनीर टिक्का मसाला", englishName: "Paneer Tikka Masala", description: "तंदूर में भुने पनीर टिक्का को मसालेदार टमाटर ग्रेवी में पकाकर परोसा गया व्यंजन।", categorySlug: "main-course", imageQuery: "paneer tikka masala gravy", isVeg: true },
  { hindiName: "पनीर कोरमा", englishName: "Paneer Korma (Rich)", description: "काजू और मलाई से बनी गाढ़ी ग्रेवी में पनीर पकाकर बनाया गया समृद्ध व्यंजन।", categorySlug: "main-course", imageQuery: "rich paneer korma", isVeg: true },
  { hindiName: "दही पनीर", englishName: "Dahi Paneer", description: "फेंटे दही और हल्के मसालों की ग्रेवी में पनीर पकाकर बनाया गया व्यंजन।", categorySlug: "main-course", imageQuery: "dahi paneer curry", isVeg: true },
  { hindiName: "पनीर कश्मीरी", englishName: "Paneer Kashmiri", description: "फल और मेवों की मीठी-नमकीन ग्रेवी में पनीर पकाकर बनाया गया कश्मीरी स्टाइल व्यंजन।", categorySlug: "main-course", imageQuery: "paneer kashmiri curry", isVeg: true },
  { hindiName: "पनीर टमाटर मसाला", englishName: "Paneer Tamatar Masala", description: "टमाटर की तीखी और खट्टी ग्रेवी में पनीर पकाकर बनाया गया सरल व स्वादिष्ट व्यंजन।", categorySlug: "main-course", imageQuery: "paneer tomato masala", isVeg: true },

  // ===================== DUM / SABJI (sabji) =====================
  { hindiName: "आलू दम पटल", englishName: "Aloo Dum", description: "छोटे आलुओं को मसालेदार ग्रेवी में धीमी आंच पर पकाकर बनाई गई पारंपरिक दम आलू सब्जी।", categorySlug: "sabji", imageQuery: "dum aloo curry", isVeg: true },
  { hindiName: "बनारसी दम आलू", englishName: "Banarasi Dum Aloo", description: "बनारसी मसालों की गाढ़ी ग्रेवी में छोटे आलुओं को दम पर पकाकर तैयार की गई सब्जी।", categorySlug: "sabji", imageQuery: "banarasi dum aloo", isVeg: true },
  { hindiName: "काश्मीरी दम आलू", englishName: "Kashmiri Dum Aloo", description: "दही और सौंफ आधारित मसालों की लाल ग्रेवी में पकाए गए काश्मीरी स्टाइल दम आलू।", categorySlug: "sabji", imageQuery: "kashmiri dum aloo", isVeg: true },
  { hindiName: "आलू गोभी दम", englishName: "Aloo Gobhi Dum", description: "आलू और फूलगोभी को मसालेदार ग्रेवी में दम पर पकाकर बनाई गई स्वादिष्ट सब्जी।", categorySlug: "sabji", imageQuery: "aloo gobi dum curry", isVeg: true },
  { hindiName: "सरन दम", englishName: "Saran Dum", description: "मौसमी सब्जियों को खास मसालों के साथ धीमी आंच पर दम देकर पकाया गया व्यंजन।", categorySlug: "sabji", imageQuery: "dum vegetable curry", isVeg: true },
  { hindiName: "बेबी कॉर्न दम", englishName: "Baby Corn Dum", description: "बेबी कॉर्न को मसालेदार ग्रेवी में दम पर पकाकर बनाई गई स्वादिष्ट सब्जी।", categorySlug: "sabji", imageQuery: "baby corn curry", isVeg: true },
  { hindiName: "कटहल दम", englishName: "Kathal Dum", description: "कच्चे कटहल को मसालों के साथ धीमी आंच पर पकाकर बनाई गई पारंपरिक सब्जी।", categorySlug: "sabji", imageQuery: "kathal jackfruit curry", isVeg: true },
  { hindiName: "लौकी दम", englishName: "Lauki Dum", description: "लौकी को मसालेदार ग्रेवी में दम पर पकाकर बनाई गई हल्की और सुपाच्य सब्जी।", categorySlug: "sabji", imageQuery: "lauki curry bottle gourd", isVeg: true },
  { hindiName: "काजू मशरूम", englishName: "Kaju Mushroom", description: "काजू के पेस्ट से बनी मलाईदार ग्रेवी में मशरूम पकाकर बनाया गया शाही व्यंजन।", categorySlug: "sabji", imageQuery: "kaju mushroom curry", isVeg: true },
  { hindiName: "बटर मशरूम", englishName: "Butter Mushroom", description: "मक्खन और टमाटर की ग्रेवी में मशरूम पकाकर बनाया गया मुलायम व स्वादिष्ट व्यंजन।", categorySlug: "sabji", imageQuery: "butter mushroom curry", isVeg: true },
  { hindiName: "मशरूम दो प्याज़ा", englishName: "Mushroom Do Pyaza", description: "प्याज़ के बड़े टुकड़ों के साथ मसालेदार ग्रेवी में पकाया गया मशरूम दो प्याज़ा।", categorySlug: "sabji", imageQuery: "mushroom do pyaza", isVeg: true },
  { hindiName: "मशरूम", englishName: "Mushroom", description: "देसी मसालों की ग्रेवी में पकाया गया साधारण पर स्वादिष्ट मशरूम व्यंजन।", categorySlug: "sabji", imageQuery: "mushroom curry indian", isVeg: true },
  { hindiName: "लहसुन सब्जी", englishName: "Lahsun Sabzi", description: "भरपूर लहसुन के तड़के और मसालों के साथ पकाई गई तीखी और खुशबूदार सब्जी।", categorySlug: "sabji", imageQuery: "garlic sabzi curry", isVeg: true },
  { hindiName: "कोफ्ता", englishName: "Kofta", description: "सब्जियों के गोले तलकर मसालेदार ग्रेवी में डुबोकर बनाया गया पारंपरिक कोफ्ता व्यंजन।", categorySlug: "sabji", imageQuery: "vegetable kofta curry", isVeg: true },
  { hindiName: "पनीर कोफ्ता", englishName: "Paneer Kofta", description: "पनीर और आलू के गोले तलकर मलाईदार ग्रेवी में परोसा गया स्वादिष्ट पनीर कोफ्ता।", categorySlug: "sabji", imageQuery: "paneer kofta curry", isVeg: true },
  { hindiName: "कटहल कोफ्ता", englishName: "Kathal Kofta", description: "कच्चे कटहल के गोले तलकर मसालेदार ग्रेवी में पकाया गया कटहल कोफ्ता।", categorySlug: "sabji", imageQuery: "kathal kofta curry", isVeg: true },
  { hindiName: "लौकी कोफ्ता", englishName: "Lauki Kofta", description: "कद्दूकस लौकी के गोले तलकर ग्रेवी में डुबोकर बनाया गया हल्का लौकी कोफ्ता।", categorySlug: "sabji", imageQuery: "lauki kofta curry", isVeg: true },
  { hindiName: "आलू कोफ्ता", englishName: "Aloo Kofta", description: "मसालेदार आलू के गोले तलकर ग्रेवी में पकाया गया स्वादिष्ट आलू कोफ्ता।", categorySlug: "sabji", imageQuery: "aloo kofta curry", isVeg: true },
  { hindiName: "गोभी कोफ्ता", englishName: "Gobhi Kofta", description: "फूलगोभी के गोले तलकर मसालेदार ग्रेवी में परोसा गया गोभी कोफ्ता।", categorySlug: "sabji", imageQuery: "gobhi kofta curry", isVeg: true },
  { hindiName: "मलाई कोफ्ता", englishName: "Malai Kofta", description: "पनीर और आलू के मुलायम गोलों को मलाईदार काजू ग्रेवी में डुबोकर बनाया गया प्रीमियम व्यंजन।", categorySlug: "sabji", imageQuery: "malai kofta", isVeg: true },
  { hindiName: "सोया बड़ी मसाला", englishName: "Soya Badi Masala", description: "सोया बड़ी को प्याज़-टमाटर की मसालेदार ग्रेवी में पकाकर बनाई गई सब्जी।", categorySlug: "sabji", imageQuery: "soya chunks masala curry", isVeg: true },
  { hindiName: "मेज सोया चोखा", englishName: "Mixed Soya Chokha", description: "सोया बड़ी को मसालों के साथ भूनकर मसलकर बनाया गया देसी अंदाज़ का चोखा।", categorySlug: "sabji", imageQuery: "soya chokha", isVeg: true },
  { hindiName: "पालक बैंगन आलू", englishName: "Palak Baingan Aloo", description: "पालक, बैंगन और आलू को मिलाकर मसालों के साथ पकाई गई मिश्रित सब्जी।", categorySlug: "sabji", imageQuery: "palak baingan aloo curry", isVeg: true },
  { hindiName: "मिक्स सब्जी", englishName: "Mix Sabzi", description: "कई मौसमी सब्जियों को मिलाकर देसी मसालों के साथ पकाई गई घरेलू स्वाद वाली मिक्स सब्जी।", categorySlug: "sabji", imageQuery: "mix vegetable curry", isVeg: true },
  { hindiName: "मिक्स वेज फ्राई", englishName: "Mix Veg Fry", description: "मिली-जुली सब्जियों को हल्के तेल और मसालों में भूनकर बनाई गई सूखी सब्जी।", categorySlug: "sabji", imageQuery: "mix veg fry dry", isVeg: true },
  { hindiName: "लौकी सब्जी", englishName: "Lauki Sabzi", description: "लौकी को हल्के मसालों के साथ पकाकर बनाई गई सुपाच्य और सेहतमंद सब्जी।", categorySlug: "sabji", imageQuery: "lauki sabzi", isVeg: true },
  { hindiName: "भिंडी सब्जी", englishName: "Bhindi Sabzi", description: "भिंडी को प्याज़-मसालों के साथ भूनकर बनाई गई पारंपरिक सूखी भिंडी सब्जी।", categorySlug: "sabji", imageQuery: "bhindi sabzi okra", isVeg: true },
  { hindiName: "कोहड़ा चना मसाला", englishName: "Kohda Chana Masala", description: "कद्दू और चने को मसालों के साथ पकाकर बनाई गई देसी स्टाइल की सब्जी।", categorySlug: "sabji", imageQuery: "pumpkin chana curry", isVeg: true },

  // ===================== DRY SABZI (sabji) =====================
  { hindiName: "बैंगन", englishName: "Baingan (Brinjal)", description: "बैंगन को मसालों के साथ भूनकर बनाई गई सूखी पारंपरिक सब्जी।", categorySlug: "sabji", imageQuery: "baingan sabzi brinjal", isVeg: true },
  { hindiName: "करेला", englishName: "Karela (Bitter Gourd)", description: "करेले को मसालों के साथ कुरकुरा भूनकर बनाई गई पारंपरिक सूखी सब्जी।", categorySlug: "sabji", imageQuery: "karela sabzi bitter gourd", isVeg: true },
  { hindiName: "आलू", englishName: "Aloo (Potato)", description: "आलू को हल्के मसालों के साथ भूनकर बनाई गई सादी और सर्वप्रिय सब्जी।", categorySlug: "sabji", imageQuery: "aloo sabzi potato dry", isVeg: true },
  { hindiName: "परवल", englishName: "Parwal (Pointed Gourd)", description: "परवल को मसालों के साथ भूनकर बनाई गई हल्की और पौष्टिक सूखी सब्जी।", categorySlug: "sabji", imageQuery: "parwal sabzi pointed gourd", isVeg: true },
  { hindiName: "भिंडी", englishName: "Bhindi (Okra)", description: "भिंडी को कुरकुरा होने तक भूनकर मसालों के साथ बनाई गई सूखी सब्जी।", categorySlug: "sabji", imageQuery: "bhindi okra dry sabzi", isVeg: true },
  { hindiName: "शिमला मिर्च आलू", englishName: "Shimla Mirch Aloo (Capsicum Potato)", description: "शिमला मिर्च और आलू को मिलाकर मसालों के साथ भूनकर बनाई गई सूखी सब्जी।", categorySlug: "sabji", imageQuery: "capsicum potato sabzi", isVeg: true },

  // ===================== KADHI (main-course) =====================
  { hindiName: "दही बड़ा कढ़ी", englishName: "Dahi Vada Kadhi", description: "दही और बेसन से बनी खट्टी कढ़ी में उड़द के वड़े डालकर परोसा गया पारंपरिक व्यंजन।", categorySlug: "main-course", imageQuery: "dahi vada kadhi", isVeg: true },
  { hindiName: "बूंदी कढ़ी", englishName: "Boondi Kadhi", description: "दही व बेसन की खट्टी कढ़ी में तली हुई बूंदी डालकर बनाई गई स्वादिष्ट कढ़ी।", categorySlug: "main-course", imageQuery: "boondi kadhi", isVeg: true },
  { hindiName: "बुढ़िया कढ़ी", englishName: "Budhiya Kadhi", description: "देसी मसालों और दही से बनाई गई पारंपरिक अंदाज़ की गाढ़ी कढ़ी।", categorySlug: "main-course", imageQuery: "traditional kadhi indian", isVeg: true },
  { hindiName: "पालक कढ़ी", englishName: "Palak Kadhi", description: "पालक और बेसन को दही के साथ पकाकर बनाई गई पौष्टिक हरी कढ़ी।", categorySlug: "main-course", imageQuery: "palak kadhi", isVeg: true },

  // ===================== SALAD =====================
  { hindiName: "फ्रूट सलाद", englishName: "Fruit Salad", description: "मौसमी फलों को काटकर मिलाई गई ताज़ी और रंग-बिरंगी फ्रूट सलाद।", categorySlug: "salad", imageQuery: "fruit salad bowl", isVeg: true },
  { hindiName: "गार्डन सलाद", englishName: "Garden Salad", description: "खीरा, टमाटर, गाजर व अन्य सब्जियों से सजी ताज़ी गार्डन सलाद।", categorySlug: "salad", imageQuery: "garden salad vegetables", isVeg: true },
  { hindiName: "हरा सलाद", englishName: "Hara Salad (Green Salad)", description: "हरी पत्तेदार सब्जियों और खीरे से बनी ताज़गी भरी हरी सलाद।", categorySlug: "salad", imageQuery: "green salad indian", isVeg: true },
  { hindiName: "ग्रीन सलाद", englishName: "Green Salad", description: "ताज़ी खीरा, टमाटर, गाजर और प्याज़ से बना ताज़गी भरा सलाद।", categorySlug: "salad", imageQuery: "indian green salad", isVeg: true },
  { hindiName: "थाई सलाद", englishName: "Thai Salad", description: "सब्जियों को खट्टे-मीठे थाई ड्रेसिंग के साथ मिलाकर बनाई गई चटपटी सलाद।", categorySlug: "salad", imageQuery: "thai salad vegetables", isVeg: true },
  { hindiName: "मिक्स सलाद", englishName: "Mix Salad", description: "कई सब्जियों को मिलाकर तैयार की गई रंग-बिरंगी और ताज़गी भरी मिक्स सलाद।", categorySlug: "salad", imageQuery: "mixed salad", isVeg: true },
  { hindiName: "लच्छा प्याज", englishName: "Laccha Pyaz (Onion Salad)", description: "पतले कतरे हुए प्याज़ पर नींबू और मसाला छिड़ककर बनाई गई पारंपरिक लच्छा प्याज़ सलाद।", categorySlug: "salad", imageQuery: "onion salad laccha pyaz", isVeg: true },

  // ===================== PAPAD (other) =====================
  { hindiName: "उड़द दाल पापड़", englishName: "Urad Dal Papad", description: "उड़द दाल के आटे से बना कुरकुरा और पतला सेंका या तला हुआ पापड़।", categorySlug: "other", imageQuery: "urad dal papad", isVeg: true },
  { hindiName: "मूंग दाल पापड़", englishName: "Moong Dal Papad", description: "मूंग दाल के आटे से बना हल्का और कुरकुरा पापड़।", categorySlug: "other", imageQuery: "moong dal papad", isVeg: true },
  { hindiName: "मसाला पापड़", englishName: "Masala Papad", description: "सेंके हुए पापड़ पर बारीक कटी प्याज़, टमाटर और मसाले सजाकर परोसा गया मसाला पापड़।", categorySlug: "other", imageQuery: "masala papad", isVeg: true },
  { hindiName: "जीरा पापड़", englishName: "Jeera Papad", description: "जीरे के स्वाद से भरपूर पतला और कुरकुरा पापड़।", categorySlug: "other", imageQuery: "jeera papad", isVeg: true },
  { hindiName: "लहसुन पापड़", englishName: "Lahsun Papad", description: "लहसुन के तीखे स्वाद से भरपूर कुरकुरा और खुशबूदार पापड़।", categorySlug: "other", imageQuery: "garlic papad lahsun", isVeg: true },
  { hindiName: "आलू पापड़", englishName: "Aloo Papad", description: "आलू के गाढ़े घोल से बनाकर धूप में सुखाया गया कुरकुरा पापड़।", categorySlug: "other", imageQuery: "aloo papad potato", isVeg: true },

  // ===================== DAHI VADA / RAITA (other) =====================
  { hindiName: "दही बड़ा", englishName: "Dahi Vada", description: "उड़द दाल के मुलायम वड़ों को ठंडे मीठे दही में डुबोकर मसालों से सजाकर परोसा जाने वाला व्यंजन।", categorySlug: "other", imageQuery: "dahi vada", isVeg: true },
  { hindiName: "मूंग दही बड़ा", englishName: "Moong Dahi Vada", description: "मूंग दाल के हल्के वड़ों को दही में डुबोकर मसालों के साथ परोसा गया व्यंजन।", categorySlug: "other", imageQuery: "moong dahi vada", isVeg: true },
  { hindiName: "मूंग फुलौरी", englishName: "Moong Phulori", description: "मूंग दाल के घोल से बनी हल्की और कुरकुरी फुलौरी, चटनी के साथ परोसी जाने वाली।", categorySlug: "other", imageQuery: "moong phulori fritters", isVeg: true },
  { hindiName: "बूंदी रायता", englishName: "Boondi Raita", description: "फेंटे दही में तली हुई बूंदी और मसाले मिलाकर बनाया गया ठंडा रायता।", categorySlug: "other", imageQuery: "boondi raita", isVeg: true },
  { hindiName: "खीरा रायता", englishName: "Kheera Raita", description: "कद्दूकस खीरे को दही और हल्के मसालों के साथ मिलाकर बनाया गया ठंडा रायता।", categorySlug: "other", imageQuery: "kheera raita cucumber", isVeg: true },
  { hindiName: "लौकी रायता", englishName: "Lauki Raita", description: "उबली कद्दूकस लौकी को दही और मसालों के साथ मिलाकर बनाया गया हल्का रायता।", categorySlug: "other", imageQuery: "lauki raita", isVeg: true },
  { hindiName: "मिक्स वेज रायता", englishName: "Mix Veg Raita", description: "कई सब्जियों को दही के साथ मिलाकर बनाया गया पौष्टिक मिक्स वेज रायता।", categorySlug: "other", imageQuery: "mix veg raita", isVeg: true },
  { hindiName: "पाइन एप्पल रायता", englishName: "Pineapple Raita", description: "अनानास के टुकड़ों को दही में मिलाकर बनाया गया मीठा-खट्टा रायता।", categorySlug: "other", imageQuery: "pineapple raita", isVeg: true },
  { hindiName: "अनार रायता", englishName: "Anar Raita", description: "अनार के दानों को दही और हल्के मसालों के साथ मिलाकर बनाया गया ताज़ा रायता।", categorySlug: "other", imageQuery: "pomegranate raita anar", isVeg: true },
  { hindiName: "फ्रूट रायता", englishName: "Fruit Raita", description: "मौसमी फलों को दही में मिलाकर बनाया गया मीठा और ठंडा फ्रूट रायता।", categorySlug: "other", imageQuery: "fruit raita", isVeg: true },

  // ===================== BARFI / MITHAI / HALWA / LADDU (sweet) =====================
  { hindiName: "साधी बर्फी", englishName: "Sadi Barfi (Plain Barfi)", description: "खोए से बनी नरम और हल्की मीठी सादी बर्फी।", categorySlug: "sweet", imageQuery: "plain barfi mithai", isVeg: true },
  { hindiName: "केसर बर्फी", englishName: "Kesar Barfi", description: "केसर की खुशबू और रंग से सजी खोए की मुलायम बर्फी।", categorySlug: "sweet", imageQuery: "kesar barfi saffron", isVeg: true },
  { hindiName: "ड्राई फ्रूट बर्फी", englishName: "Dry Fruit Barfi", description: "काजू, बादाम व अन्य मेवों से बनी पौष्टिक और स्वादिष्ट बर्फी।", categorySlug: "sweet", imageQuery: "dry fruit barfi", isVeg: true },
  { hindiName: "गुलाबी बर्फी", englishName: "Gulabi Barfi", description: "गुलाब के हल्के फ्लेवर और रंग से सजी सुंदर मीठी बर्फी।", categorySlug: "sweet", imageQuery: "gulabi barfi rose", isVeg: true },
  { hindiName: "रवा बर्फी", englishName: "Rava Barfi", description: "सूजी को घी में भूनकर चीनी के साथ जमाई गई मीठी रवा बर्फी।", categorySlug: "sweet", imageQuery: "rava barfi sooji", isVeg: true },
  { hindiName: "बड़ी वाली बर्फी", englishName: "Badi Wali Barfi", description: "बड़े टुकड़ों में काटी गई खोए की गाढ़ी और मलाईदार बर्फी।", categorySlug: "sweet", imageQuery: "khoya barfi mithai", isVeg: true },
  { hindiName: "दही बर्फी", englishName: "Dahi Barfi", description: "दही और खोए को मिलाकर बनाई गई हल्की मीठी बर्फी।", categorySlug: "sweet", imageQuery: "dahi barfi sweet", isVeg: true },
  { hindiName: "रसमलाई", englishName: "Rasmalai", description: "ठंडे केसर वाले दूध में डूबे मुलायम छेने के गोले, एक क्लासिक बंगाली मिठाई।", categorySlug: "sweet", imageQuery: "rasmalai indian sweet", isVeg: true },
  { hindiName: "अंगूरी रसमलाई", englishName: "Anguri Rasmalai", description: "छोटे अंगूर के आकार के छेने के गोलों को केसरी दूध में भिगोकर बनाई गई खास रसमलाई।", categorySlug: "sweet", imageQuery: "anguri rasmalai", isVeg: true },
  { hindiName: "रसगुल्ला", englishName: "Rasgulla", description: "छेने से बने मुलायम स्पंजी गोलों को चाशनी में भिगोकर बनाई गई बंगाली मिठाई।", categorySlug: "sweet", imageQuery: "rasgulla sweet", isVeg: true },
  { hindiName: "राज भोग", englishName: "Raj Bhog", description: "मेवों से भरे बड़े छेने के गोलों को केसरी चाशनी में भिगोकर बनाई गई शाही मिठाई।", categorySlug: "sweet", imageQuery: "raj bhog sweet", isVeg: true },
  { hindiName: "चमचम", englishName: "Chum Chum", description: "छेने से बनी बेलनाकार मिठाई, चाशनी में भिगोकर मेवों से सजाई गई।", categorySlug: "sweet", imageQuery: "chum chum sweet", isVeg: true },
  { hindiName: "संदेश", englishName: "Sandesh", description: "ताज़े छेने से बनाई गई हल्की मीठी और नरम बंगाली मिठाई।", categorySlug: "sweet", imageQuery: "sandesh bengali sweet", isVeg: true },
  { hindiName: "गुलाब जामुन", englishName: "Gulab Jamun", description: "गरम-गरम, मुलायम और चाशनी में डूबे गुलाब जामुन, हर मेहमान की पसंदीदा मिठाई।", categorySlug: "sweet", imageQuery: "gulab jamun dessert", isVeg: true },
  { hindiName: "काला जामुन", englishName: "Kala Jamun", description: "गहरे भूरे रंग तक तले गए खोए के जामुन, गाढ़ी चाशनी में डुबोकर परोसे जाने वाले।", categorySlug: "sweet", imageQuery: "kala jamun sweet", isVeg: true },
  { hindiName: "खीर कदम", englishName: "Kheer Kadam", description: "छेने की गोली के अंदर खीर भरकर बनाई गई अनोखी और मलाईदार मिठाई।", categorySlug: "sweet", imageQuery: "kheer kadam sweet", isVeg: true },
  { hindiName: "जामुन गिलौरी", englishName: "Jamun Gilori", description: "पान के आकार में बनाई गई खोए की खास मीठी गिलौरी मिठाई।", categorySlug: "sweet", imageQuery: "gilori sweet mithai", isVeg: true },
  { hindiName: "रस कदम", englishName: "Ras Kadam", description: "छेने की परत में रसगुल्ला भरकर बनाई गई मलाईदार और मीठी मिठाई।", categorySlug: "sweet", imageQuery: "ras kadam sweet", isVeg: true },
  { hindiName: "बर्फी", englishName: "Barfi", description: "खोए और चीनी से बनी क्लासिक मीठी और मुलायम बर्फी।", categorySlug: "sweet", imageQuery: "barfi mithai", isVeg: true },
  { hindiName: "कालाकंद", englishName: "Kalakand", description: "गाढ़े दूध और छेने को पकाकर बनाई गई दानेदार व मुलायम मिठाई।", categorySlug: "sweet", imageQuery: "kalakand sweet", isVeg: true },
  { hindiName: "गाजर हलवा", englishName: "Gajar Halwa (Carrot Halwa)", description: "गाजर को दूध व घी में धीमी आंच पर पकाकर मेवों से सजाया गया मशहूर गाजर हलवा।", categorySlug: "sweet", imageQuery: "gajar halwa carrot halwa", isVeg: true },
  { hindiName: "बेसन हलवा", englishName: "Besan Halwa", description: "बेसन को घी में भूनकर चीनी की चाशनी में पकाया गया गरमागरम बेसन हलवा।", categorySlug: "sweet", imageQuery: "besan halwa", isVeg: true },
  { hindiName: "मूंग हलवा", englishName: "Moong Halwa", description: "भीगी मूंग दाल को पीसकर घी में भूनकर बनाया गया गाढ़ा और स्वादिष्ट मूंग हलवा।", categorySlug: "sweet", imageQuery: "moong dal halwa", isVeg: true },
  { hindiName: "आटा हलवा", englishName: "Atta Halwa", description: "गेहूं के आटे को घी में भूनकर चाशनी में पकाया गया पारंपरिक आटा हलवा।", categorySlug: "sweet", imageQuery: "atta halwa wheat", isVeg: true },
  { hindiName: "शाही सोहन हलवा", englishName: "Shahi Sohan Halwa", description: "मेवों से सजा हुआ गाढ़ा, चिपचिपा और शाही स्वाद वाला सोहन हलवा।", categorySlug: "sweet", imageQuery: "sohan halwa", isVeg: true },
  { hindiName: "लौकी हलवा", englishName: "Lauki Halwa (Bottle Gourd Halwa)", description: "कद्दूकस लौकी को दूध व घी में पकाकर मेवों से सजाया गया हल्का मीठा हलवा।", categorySlug: "sweet", imageQuery: "lauki halwa bottle gourd", isVeg: true },
  { hindiName: "सिंघाड़ा हलवा", englishName: "Singhara Halwa", description: "सिंघाड़े के आटे को घी में भूनकर चाशनी के साथ पकाया गया व्रत में लोकप्रिय हलवा।", categorySlug: "sweet", imageQuery: "singhara halwa water chestnut", isVeg: true },
  { hindiName: "गजरेला हलवा", englishName: "Gajrela Halwa", description: "गाजर और खोए को मिलाकर धीमी आंच पर पकाया गया गाढ़ा मीठा हलवा।", categorySlug: "sweet", imageQuery: "gajrela halwa carrot", isVeg: true },
  { hindiName: "सेव हलवा", englishName: "Sev Halwa", description: "सेवइयों को घी में भूनकर दूध व चीनी के साथ पकाया गया मीठा सेव हलवा।", categorySlug: "sweet", imageQuery: "sewaiyan halwa", isVeg: true },
  { hindiName: "काजू कतली", englishName: "Kaju Katli", description: "काजू के महीन पेस्ट से बनी चांदी के वर्क से सजी क्लासिक हीरे के आकार की मिठाई।", categorySlug: "sweet", imageQuery: "kaju katli", isVeg: true },
  { hindiName: "पिस्ता बर्फी", englishName: "Pista Barfi", description: "पिस्ते के गाढ़े पेस्ट से बनी हरी रंगत वाली प्रीमियम बर्फी।", categorySlug: "sweet", imageQuery: "pista barfi pistachio", isVeg: true },
  { hindiName: "बादाम बर्फी", englishName: "Badam Barfi", description: "बादाम के पेस्ट से बनी पौष्टिक और मलाईदार प्रीमियम बर्फी।", categorySlug: "sweet", imageQuery: "badam barfi almond", isVeg: true },
  { hindiName: "नारियल बर्फी", englishName: "Nariyal Barfi (Coconut Barfi)", description: "कद्दूकस नारियल को चीनी के साथ पकाकर जमाई गई मीठी नारियल बर्फी।", categorySlug: "sweet", imageQuery: "coconut barfi nariyal", isVeg: true },
  { hindiName: "चॉकलेट बर्फी", englishName: "Chocolate Barfi", description: "खोए और कोको को मिलाकर बनाई गई फ्यूज़न स्टाइल चॉकलेट बर्फी।", categorySlug: "sweet", imageQuery: "chocolate barfi fusion sweet", isVeg: true },
  { hindiName: "मोतीचूर लड्डू", englishName: "Motichoor Laddu", description: "बेसन की महीन बूंदी से बना गोल और मुलायम मोतीचूर लड्डू, हर शुभ मौके की मिठाई।", categorySlug: "sweet", imageQuery: "motichoor laddu", isVeg: true },
  { hindiName: "बेसन लड्डू", englishName: "Besan Laddu", description: "बेसन को घी में भूनकर चीनी के साथ गोल आकार में बनाया गया पारंपरिक लड्डू।", categorySlug: "sweet", imageQuery: "besan laddu", isVeg: true },
  { hindiName: "बूंदी लड्डू", englishName: "Boondi Laddu", description: "मीठी बेसन की बूंदी को गोल आकार में बांधकर बनाया गया क्लासिक बूंदी लड्डू।", categorySlug: "sweet", imageQuery: "boondi laddu", isVeg: true },
  { hindiName: "गोंद लड्डू", englishName: "Gond Laddu", description: "खाने योग्य गोंद, मेवों और घी से बना पौष्टिक और सर्दियों का खास लड्डू।", categorySlug: "sweet", imageQuery: "gond laddu", isVeg: true },
  { hindiName: "गुड़ लड्डू", englishName: "Gud Laddu", description: "गुड़ और तिल या मेवों को मिलाकर बनाया गया सेहतमंद देसी लड्डू।", categorySlug: "sweet", imageQuery: "gud laddu jaggery", isVeg: true },
  { hindiName: "गुझिया", englishName: "Gujiya", description: "मावा और मेवों की स्टफिंग भरकर तली गई त्योहारों की पारंपरिक मिठाई गुझिया।", categorySlug: "sweet", imageQuery: "gujiya sweet", isVeg: true },
  { hindiName: "तिल गुड़ गुझिया", englishName: "Til Gud Gujiya", description: "तिल और गुड़ की मीठी स्टफिंग भरकर तली गई खास सर्दियों की गुझिया।", categorySlug: "sweet", imageQuery: "til gud gujiya sesame", isVeg: true },
  { hindiName: "मावा गुझिया", englishName: "Mawa Gujiya", description: "मावा और मेवों की गाढ़ी स्टफिंग भरकर तली गई पारंपरिक मावा गुझिया।", categorySlug: "sweet", imageQuery: "mawa gujiya", isVeg: true },
  { hindiName: "जलेबी", englishName: "Jalebi", description: "घोल को तेल में कुंडलीदार आकार में तलकर गरम चाशनी में डुबोई गई कुरकुरी जलेबी।", categorySlug: "sweet", imageQuery: "jalebi sweet", isVeg: true },
  { hindiName: "इमरती", englishName: "Imarti", description: "उड़द दाल के घोल से बनी फूल के आकार की चाशनी में डूबी मिठाई।", categorySlug: "sweet", imageQuery: "imarti sweet", isVeg: true },
  { hindiName: "मालपुआ", englishName: "Malpua", description: "मैदा और दूध के घोल से बने पैनकेक जैसे मालपुए, चाशनी में डुबोकर परोसे जाने वाले।", categorySlug: "sweet", imageQuery: "malpua sweet pancake", isVeg: true },
];